### ISSUE TITLE
Inconsistency with folder-documents.svg in Curvy Design No. 5

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-folders#10]
Hi, looking at the folder designs in Curvy Style No. 5, I noticed s.th. that to me looks like an inconsistency with `folder-documents.svg`. The white symbol for documents (specifically the "frame") appears very thin when compared to all the other white symbols.

Comparative screenshots of Curvy Style No. 5 and Default Style (Ubuntu 14.10, Nautilus/Files):

![folders_curvy](https://cloud.githubusercontent.com/assets/7164227/6227920/d714f086-b6a5-11e4-9776-0bcea4c0557b.png)
![folders_default](https://cloud.githubusercontent.com/assets/7164227/6227922/dc9353e0-b6a5-11e4-89de-35f29e7a449d.png)

More detailed comparative screenshots of `folder-documents.svg` and e.g. of `user-desktop.svg` (48x48):

![folder-documents](https://cloud.githubusercontent.com/assets/7164227/6227931/ff7e58fa-b6a5-11e4-9bd6-1f7f4cb9087f.png)
![user-desktop](https://cloud.githubusercontent.com/assets/7164227/6227935/0362a4da-b6a6-11e4-9829-9dee2d7a0407.png)

This appears to relate specifically to sizes 48x48 and 96x96. For comparison, here is a screenshot of `folder-documents.svg` in size 256x256, thickness of the white symbol all fine here:

![folder-documents_256x256](https://cloud.githubusercontent.com/assets/7164227/6228047/489a61c2-b6a7-11e4-9ed0-43aec6eb8be3.png)

**Comment by Foggalong** [comment]
This will have risen from the design of the style itself. Because of the symbol positioning it has to be smaller that it would be in other styles, and so each size needed to be redone specifically. From this slight differences will have arisen unnoticed. I'll check the documents one now and fix it, but if you notice any other garish ones just let me know :)
