### ISSUE TITLE
Recommended way to assign a custom folder icon?

### ISSUE THREAD

**Issue by mendhak** [numixproject/numix-folders#100]
After running the script, all the regular Places folders get the numix folder icons (Documents, Downloads...)

Suppose I create an RSS folder in my home directory.  There's a `*-rss.svg` folder icon.  

1. Would I assign the folder icon `*-rss.svg` manually or is there a clever way to do this?

2. If I rerun the numix-folders script and switch styles, is there a simple way to switch the styles on these 'custom' folders?

I'm running Ubuntu 15.04; I realize this is a noobish question but finding answers on this has been difficult; possibly because I'm not sure what to search for.

**Comment by wa4557** [comment]
The colour change in the script is always global (which means that all the colour for all the folders will be changed) If you want to change the colour of one specific folder check out this ppa (which has amazing Numix support): https://launchpad.net/~costales/+archive/ubuntu/folder-color Depending on your file-manager you have to install different packages (nemo, caja, nautilus are supported).

This then gives you a new option in the right click context menu, that allows to change one colour of one folder individually.

The colour will also stay the same when changing the style :)

**Comment by wa4557** [comment]
Ah i misinterpreted your question sorry. 
Try:
```
gvfs-set-attribute /path/to/folder/ metadata::custom-icon-name folder-rss
```

**Comment by mendhak** [comment]
Perfect - that `gvfs-set-attribute` command is exactly what I need.  Thanks, much appreciated.

**Comment by wa4557** [comment]
You're welcome. @Foggalong Is this maybe something that should be included in the README? I doubt that this is common knowledge, and all those fancy custom icons are pretty useless if no one can use them :)

**Comment by Foggalong** [comment]
Chose not to include it because it doesn't unless you're using GNOME :(
