### ISSUE TITLE
Add a GUI

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-folders#102]
A few people have brought up that it would be good to have a GUI for the script. This would especially be useful for the custom folder colours since it would allow people to test things out with the gtk colour chooser. Here's a list of things I'd like to be implemented as part of the GUI:

* [x] flag which allows the user to run the script in CLI mode
* [x] drop down menu to pick the base style
* [x] drop down menu to pick the colour
* [x] custom item in colour list which will causes 1-3 new variable buttons to appear
* [x] gtk-color-picker to choose the custom colour buttons
* [x] preview icon (`user-home.svg`) which shows what current options will look like

**Comment by wa4557** [comment]
I started fiddling around a little bit, but it seems that zenity is not powerful enough :( Do you have any preferences for the toolkit? (if we want to do this using bash `gtkdialog` would be a reasonable choice)

**Comment by Foggalong** [comment]
Yeah, that would be fine with me! :)

**Comment by wa4557** [comment]
So I get that you're thinking of one big window where you can choose everything, am I right? The other way would be to have first a window for style then a window for colour etc...

**Comment by Foggalong** [comment]
Threw something together very roughly in glade to show what I was rambling on about in the op. Had the further thought that if the 3 custom boxes are always visible then people can first select a default colour (i.e. red) and the move from there if they so wish.

![screenshot_2015-07-23_20-43-14](https://cloud.githubusercontent.com/assets/5920259/8860407/7cef14d2-317b-11e5-85d6-284cad55eb6d.png)

**Comment by wa4557** [comment]
Cool, that should be fairly easy :)

**Comment by bil-elmoussaoui** [comment]
I think that you should show others folders that use a symblo; for example : music...

**Comment by wa4557** [comment]
I guess `user-home` is the most appropriate

**Comment by Foggalong** [comment]
Just one is fine for a preview. Ideally it'd be displayed at 64 or 96 px so substantially bigger than in my mockup

**Comment by wa4557** [comment]
First try:
![unbenannt](https://cloud.githubusercontent.com/assets/6475757/8862759/576d8a8c-3193-11e5-8dfb-f1dda6bda2a6.png)

**Comment by wa4557** [comment]
I have it almost ready. Just a few quirks I have to polish :) unfortunately gtkdialog is probably the worst documented piece of software i've ever encountered :(

**Comment by Foggalong** [comment]
Worse than the GJS with GNOME Shell? D:

**Comment by wa4557** [comment]
I've Never used GJS but it can't be worse :P

**Comment by Foggalong** [comment]
There literally isn't any documentation for the GJS GNOME Shell API, that's why development of Atom has been so slow. It's literally a case of trial and error for working out how to do things :'(

**Comment by satya164** [comment]
Shouldn't you be using GtkApplication instead of GtkDialog?

**Comment by wa4557** [comment]
with gtkdialog I mean this: https://code.google.com/p/gtkdialog/
 is reasonable because it allows bash programming

**Comment by wa4557** [comment]
Ok. Although it's almost finished there are a few critical bugs I cannot iron out using gtkdialog, be it bcause there are crucial signals missing for a lot of widgets, or there are bugs in the software (as far as I understand).  

This means that I cannot give that to you as is it is now, would it be ok to rewrite the whole thing using a different toolkit? (I'd love to do it using pygtk, I can also use something else) That should be fairly easy because I already have the structure and general idea

**Comment by bil-elmoussaoui** [comment]
I guess that using Pygtk is a good idea ;)

**Comment by wa4557** [comment]
@dirtydancing @bil-elmoussaoui @Foggalong and whoever else it may concern: I've finished the GUI and it's working pretty great, nevertheless there are probably some (presumably small) bugs. Anyone fancy to test it?

https://github.com/wa4557/numix-folders/tree/gui/gui

Just run it (for now until I added it to the the bash script) using: `./gui "red"` or `./gui "custom" "#000000" "#000000" "#000000"` (or any other combination thereof)

Btw: If there's a pro using GTK: I'm still trying to find out how to minimize the width of the entry boxes (that's basically the only thing I kinda dislike about this GUI)

**Comment by bil-elmoussaoui** [comment]
@wa4557 worked for me, just some few things that you can fix easily 
- use except & try for copyfile to handle if a file does not exists
-  in the line 32 and 36 why not using color.lower() in .. instead for what you've done?

**Comment by wa4557** [comment]
1) Good point, I am however still trying to think of a way to do this without copying any files on the harddisk, but keeping the svg in the memory somehow...

2) True, I'll change that

**Comment by bil-elmoussaoui** [comment]
Last thing, i think you can read the config file directly using python ;) I don't know if you're going to only use the GUI or you will keep the bash script file too

**Comment by wa4557** [comment]
The bash script will definitely stay :) I already have a good plan to implement this script in the bash script

**Comment by wa4557** [comment]
I added the python script to the bash script. Seems to work. So if you want to test this you may also use this one :) https://github.com/wa4557/numix-folders/tree/guiconfig

**Comment by bil-elmoussaoui** [comment]
Good work!! Just one thing, the icon for style 1 does not change as it should be. And there's no way to chose which style you want to use as base for the colours?
![screenshot 31-07-2015 21 42 24](https://cloud.githubusercontent.com/assets/7660997/9015941/153464ac-37cd-11e5-9a1d-c7ec4627cf8c.png)

**Comment by wa4557** [comment]
The symbol in style is actually not a symbol but a hole in the baseplate therefore it cannot be changed. Sure there is: use the combobox and select for example "style 1"

**Comment by bil-elmoussaoui** [comment]
Ah i just didn't saw that :P closing the application will anyway call the bash script :/  and i think you can add this to Gtk.entry ```self.colorentry2.set_max_length(7) ``` or just make it 6 and remove the # from the Gtk.entry

**Comment by bil-elmoussaoui** [comment]
One last thing, the icons colour should be updated at first start, you can try to change the icons to any custom colour, restart the application, the colours are the default ones and the icons are not..In the first start update, you can add there later a way to check for config file saved configurations.

**Comment by Foggalong** [comment]
Style 1 is special. Most of the icons in Numix were designed in the same way originally. Just one colour and then everything else cutout

**Comment by bil-elmoussaoui** [comment]
In this case, i think the best way is to add an information icon near the style and explain that as almost every user will think it's a bug

**Comment by Foggalong** [comment]
Easier than that, just have the non-used colours dull out and become unclickable if style 1 is selected. That'd be in line with how the script handles that stuff.

Adding information tooltips could get messy if we made more styles that did other things like it.

**Comment by bil-elmoussaoui** [comment]
Well that's a better idea :+1:

**Comment by wa4557** [comment]
Good idea I'll to that tomorrow!

Bilal Elmoussaoui <notifications@github.com> schrieb am Fr., 31.07.2015,
22:15:

**Comment by wa4557** [comment]
@bil-elmoussaoui well the default icons are the ones defined in the config file (i.e. Previous settings) i guess that makes sense

**Comment by wa4557** [comment]
Ok I implemented the latet features and cleaned the code up (a lot; initially I was too stupid to use proper Phython code), From my point of view it is finished

**Comment by bil-elmoussaoui** [comment]
Awesome work ;) just i don't know why there's still some prints in the code?

**Comment by wa4557** [comment]
Those prints are basically the return value for the bash function (that's the best way to share variables between bash and python)

**Comment by dirtydancing** [comment]
Great work! I finally got around to give this a try. Two initial points:

1) The preview for style 5 appears to be wrong for the symbol colour. E.g., when choosing blue, the symbol colour for style 5 turns dark blue, but it should remain "white", just as it actually does when applied.

2) Is there a possibility to have the GUI display s.th. like "applying..." to indicate that the changes are being applied? Right now, the GUI disappears right after the selection is made, but it takes some time until the changes are visible. This might confuse users.

**Comment by wa4557** [comment]
1) Good finding, that's actually pretty hard to implement I have to think about this more carefully...

2) With ease, I'll do that this evening

**Comment by wa4557** [comment]
@dirtydancing I fixed your first point now (required quite some bit of recoding). Fancy to try again? I experienced no further problems...

**Comment by dirtydancing** [comment]
Confirmed that the symbol colour for style 5 for the predefined colours is displayed correctly now :+1: 

Screenshot (Arch/GNOME, default Adwaita GTK theme):

![gui_arch_gnome](https://cloud.githubusercontent.com/assets/7164227/9118396/5ca774b2-3c70-11e5-9f88-3443a79b5166.png)

Some more suggestions/thoughts/ideas:

3) Maybe it would be clearer to have a fixed size/monospace font for the hex values, so the values have the same length in all three hex value lines?

4) How about a slightly larger size for the folder previews? Or how about slightly more space inbetween the folder previews? I really like how all 6 styles are showing.

5) Maybe have a headline "Colour" above the colour selection? At first sight, currently this might be a little confusing because e.g. "Style 1" appears on the left as well as for an option in the dropdown menu.

6) Possibly alternatively to 5), how about left-aligning the dropdown menu box with the three colours below, so it might be clearer that these belong together?

7) I like very much that the last setting is kept when running the GUI again. Expanding on the saving of settings: if possible, how about giving an option to save a couple of settings with individual names that can also be accessed via a (separate) dropdown menu for "saved settings" (style and colour/s)? This separate box could e.g. be placed at the top of the right side options, next to "Style 1". Then again, there might not really be a use case for this, as the last settings are preserved anyways. But e.g. this could be useful if let's say a user goes back to the default, but then would like to return to a previous individual custom setting.

**Comment by wa4557** [comment]
3) Seems reasonable I'll try it out and see how it looks
4) Not doable (except for the spacing of course). The next size is 64x64. That's too big
5 & 6) I'm gonna go with the headline and also try aligning the two boxes
7) This would require a huuuge rewriting. I'm not going to do this right now, that's just too much work for this arguably not extremely useful feature

**Comment by dirtydancing** [comment]
Sounds great to me :+1:

**Comment by wa4557** [comment]
Ok I fixed all of the issues you raised, thanks for the suggestions :)

**Comment by dirtydancing** [comment]
Sweet! Slightly more spacing for the 6 folder styles, left-aligned dropdown selection box, and best of all clearer monospace font for the three colour hex values - love it! :)

Is this a bold font? Maybe this new one is a bit too striking overall? But imo definitely an improvement.

Screenshot:

![gui_2](https://cloud.githubusercontent.com/assets/7164227/9121252/6b0baa12-3c81-11e5-8b0e-f8e527320811.png)

One more thing: 2) from above, indicating that change is in progress, apparently is not addressed yet?

**Comment by wa4557** [comment]
2) is harder to code than expected, because it's hard to launch python guis from bash and talk to them, but I'm working on it

The font is the system font, so which font is used depends on your system mono font

**Comment by bil-elmoussaoui** [comment]
i think you can just show a notification to the user ?

**Comment by wa4557** [comment]
you mean something like `notify-osd`? The problem is that's probably not platform independent :(

**Comment by wa4557** [comment]
Ah nevermind there seems to be a gtk3 function that does exactly this :dancer:

**Comment by bil-elmoussaoui** [comment]
yeah, i don't know where we can informations about that :/

**Comment by bil-elmoussaoui** [comment]
Awesome 😎

**Comment by wa4557** [comment]
Cool. I added a notification message as well, can some non Ubuntu users try it if it works on their machine as well?

**Comment by dirtydancing** [comment]
Arch/GNOME: When is the notification message supposed to show up? No notification shown here.

**Comment by dirtydancing** [comment]
What I was thinking of is that the GUI stays visible until the change is completed, with an indication that the changes are being applied or the like. Currently, right after pressing "OK", the GUI closes right away.

**Comment by wa4557** [comment]
After pressing ok a message should show up :(
Yeah you're idea isn't really doable, because I can't find a way to let th gui know when the bash script is finished

**Comment by dirtydancing** [comment]
I see. Well, unfortunately no message showing up here with Arch/GNOME after pressing "OK"

**Comment by dirtydancing** [comment]
In the end, I figure this is not a big deal, as the user should be aware that the changes are being applied after pressing "OK" :) It sometimes just seems to take a little while, I guess depending on your machine.

**Comment by wa4557** [comment]
Agreed, plus at least for those distributions that support system notifications a notification will show up :)

**Comment by dirtydancing** [comment]
Yeah, and for Arch/GNOME, this might also simply be a system setting that I have not come across yet.

**Comment by wa4557** [comment]
Does it say something on the command line?

**Comment by dirtydancing** [comment]
Traceback (most recent call last):
  File "./gui/notification", line 7, in <module>
    n.show()
GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files (2)

**Comment by dirtydancing** [comment]
Well, I guess this might just be a matter of finetuning with Arch/GNOME. E.g., just to check, I installed the notify-osd package for Arch, and now this notification was showing up indeed:

![notify-osd](https://cloud.githubusercontent.com/assets/7164227/9123747/e0c014ae-3c91-11e5-82a6-9002b95bc007.png)

**Comment by bil-elmoussaoui** [comment]
If you open the bash script without root permissiong you will get this message 
```
You appear to have Numix installed globally.
Please run this script again as root.

Folder change complete!
```
I think that the `Folder change complete!` should not be shown in this case?

**Comment by dirtydancing** [comment]
Continuing with the numbering from my end that I started above:

8) Is there a flag to run `numix-folders` from the command line, without the GUI?

9) Relating to 8): Would it make sense to include a manpage for `numix-folders`, to document such flag?

10) Colour picker: would it be possible/useful to have a wheel colour selection GUI rather than the current selection method? Something like this, imo more intuitive, but this might just be personal preference:

![colour-wheel](https://cloud.githubusercontent.com/assets/7164227/9132411/a0ea9f36-3cf3-11e5-8547-ab5b70f4d8ec.png)

As a comparison, this is the layout of the current custom colour picker:

![colour-picker_current](https://cloud.githubusercontent.com/assets/7164227/9132666/68e111ae-3cf5-11e5-9074-3714b599291a.png)

11) Colour picker: would it be possible/useful to add (below the hex value, possibly in one line) the HSL values (hue, saturation, lightness), to allow colour adjustment by these parameters? On the other hand, this might be too confusing/complex for the purpose of a basic colour picker.

12) Colour picker (detail): would it be possible/useful to have the colour picker display the colour once the hex value is entered, without the need to press "Return"? This would also be consistent with the main GUI, because the colour preview boxes on the left of the three hex values also change once the hex value is entered, no need to press "Return".

13) Is there an icon for `numix-folders`? Currently, e.g. in Arch/GNOME, the dash is showing a "?"-symbol with the name "Gui". Screenshot:

![gui](https://cloud.githubusercontent.com/assets/7164227/9132921/717bb6dc-3cf7-11e5-96b7-e5c5b3b5a99c.png)

**Comment by wa4557** [comment]
8) Yes run it using `-t` or `--cli`
9) probably, but there is also the `-h` flag
10) That's the way the gtk colour picker is designed in gtk3 nothing I can do about that
11) Would be possible, but it would be relatively hard to implement because it would require some rewriting. I'd rather wouldn't do it for now
12) Again, the colourpicker is not implemented by me, it's the standard one from gtk
13) I guess an icon will make sense as soone there is a desktop file

**Comment by wa4557** [comment]
@bil-elmoussaoui: Using the gui or the command line?

**Comment by dirtydancing** [comment]
As to 13), an icon for `numix-folders`: how about something like this: classic style 1 with a couple of predefined primary and secondary colours. Screenshots in sizes large, original (48x48) and small:

![size_large](https://cloud.githubusercontent.com/assets/7164227/9140213/bc4e5d80-3d2f-11e5-81c2-f9a6702c1229.png)
![size_original](https://cloud.githubusercontent.com/assets/7164227/9140214/c3608fda-3d2f-11e5-9f2e-edcb773de2b5.png)
![size_small](https://cloud.githubusercontent.com/assets/7164227/9140217/c77e2014-3d2f-11e5-8c0d-484eb8c9d24e.png)

**Comment by wa4557** [comment]
I like it. Now you just need to make a circle icon as well :)

dirtydancing <notifications@github.com> schrieb am Fr., 07.08.2015, 18:14:

**Comment by dirtydancing** [comment]
Yeah, you are right :) Anyways, I started off with a Numix base icon because this one should also be in Numix base, as esp. for numix-folders there is a use case of people using Numix base with it (not Circle).

**Comment by wa4557** [comment]
I guess this icon should rather be placed in hicolor not in numix

dirtydancing <notifications@github.com> schrieb am Fr., 07.08.2015, 19:22:

**Comment by dirtydancing** [comment]
Agreed that placing it in `hicolor` makes sense. Still, imo placing it in Numix base would be fine, too, as there is no use case of someone using numix-folders without using Numix base, or is there? But indeed, if installed with numix-folders itself, `hicolor` seems to be the place to go for this "generic" app icon.

**Comment by wa4557** [comment]
There's probably no usecase but if someone decides to use another theme the app itself might still be installed and show up in the dash, launcher etc...

**Comment by dirtydancing** [comment]
13) Icons for `hicolor` (scalable/apps) and for `Numix-Circle`, cleaned up and ready to be pushed:

![hicolor](https://cloud.githubusercontent.com/assets/7164227/9149778/08092252-3dba-11e5-83ff-a213d4548758.png)

![circle](https://cloud.githubusercontent.com/assets/7164227/9149779/089ad67a-3dba-11e5-9975-f2b06c039d5a.png)

**Comment by dirtydancing** [comment]
9) Agreed that (at least for the time being) the help flag `-h` is fine for the options documentation:

Screenshot of help flag output:

![help-flag](https://cloud.githubusercontent.com/assets/7164227/9149798/663215cc-3dbb-11e5-8b6f-d48187a1bf43.png)

**Comment by dirtydancing** [comment]
@bil-elmoussaoui It seems that I cannot reproduce that running the script without root (command line) results in `Folder change complete!`

Output on my end is only:
`You appear to have Numix installed globally.`
`Please run this script again as root.`

**Comment by wa4557** [comment]
And if you run it wnot in teminal mode, gksudo should show up asking for the password

**Comment by dirtydancing** [comment]
Yes, that is the case on my end as well: if not run in terminal mode, gksudo will ask for the password.

The output cited above only appears in terminal mode, and as far as I can tell, all is looking just fine.

**Comment by bil-elmoussaoui** [comment]
i was using an older version :P everything works fine here

**Comment by dirtydancing** [comment]
Quick info: I have created pull requests for the `numix-folders.svg` icons here (in the new folder `icons`) and over at Numix-Circle, cf. https://github.com/numixproject/numix-folders/pull/105 and https://github.com/numixproject/numix-icon-theme-circle/pull/2474. To me, the icon name `numix-folders.svg` makes sense, and I figure it does not hurt to already have the icons in place.

**Comment by bil-elmoussaoui** [comment]
I tried again the numix-folders to be sure that everything works fine ;) 
![screenshot from 2015-08-12 22-46-26](https://cloud.githubusercontent.com/assets/7660997/9236289/40b701cc-4144-11e5-8252-5e6890b2d542.png)
@wa4557 Just one last thing to implement/fix, if the user does not change in thing from the older configuration file and just open the interface and click on "ok" again; the script should not change the icons again

**Comment by wa4557** [comment]
Good point, but that's not possible. The gui doesn't change anything it just reports the selected colours to the bash script, which then takes care of the folder change. 
The problem is that the ash script has no idea (and can't have an idea) if the folders are already changed or not...

**Comment by bil-elmoussaoui** [comment]
Well, do you read the default icons using bash or python? if it's using bash, you can do that to check if the "received" colours are the same as the one in the configuration file. If not change the icons, if it's show an other message

**Comment by wa4557** [comment]
I see what you mean, and this is definitely something we could/should implement. However I guess this should be done in a subsequent PR since it has nothing to do with the GUI per se

**Comment by wa4557** [comment]
@Foggalong Because I'm saw it just now: You only ticked 4 of the 6 ticks in your original post. Does that mean that you want something changed in the design of the gui?

**Comment by Foggalong** [comment]
Ah, I thought I'd commented as well! Must not have sent properly :(

Yeah I've not closed the issue because of the styles being radio button rather than a drop down. I really like the radio button design and how it allows you to see what all the styles will look like, but it's going to become unwieldy quite quickly as more and more styles are added. We've gone through 6 styles in 2 years, so imagine in the future when there could be 12 or 18 different styles to pick from.

The style menu turning from radio to dropdown would also necessitate a preview icon so the user could see what the outcome of the script would be.

-----

On a separate note, I'm not sure I ever thanked you for dealing with the GUI. If I didn't, then thank you. It really had been a massive help and has moved this project from the little scrappy script I started with :)

**Comment by wa4557** [comment]
You're welcome, always good to freshen up GUI coding knowledge :)

First of all: It would be fairly easy to change the radiobuttons to a dropdown menu. 
But I think we shouldn't change that right now. I did that on purpose because I think it is waaay more user friendly this way. You immediately see what you're choosing without the necessity to click on an additional combo box. If more styles are added along the way, we can change that within half an hour. 

So as long as not more styles are added I'd argue to keep it that way. That being said: If you really want to change that I can of course change that :)

**Comment by dirtydancing** [comment]
My impression: the current design with all 6 folder styles visible at once in a vertical row is brilliant!

**Comment by wa4557** [comment]
Another suggestion: if you open a new branch I could upload there the new version with the two comboboxes, and as soon as more styles are introduced and the current design doesn't work anymore, we can switch from the current design to the new one 
But again: for now I would argue that it makes more sense to keep the current design, because it gives you way more information without looking bad (in my subjective opinion of course)

**Comment by Foggalong** [comment]
I'd like to switch to the dropdown now if that's okay. I know there's definitely another style to add as soon as I've got time to do so, with a possible 2 more over the next few months.

To make it a bit more user friendly though, maybe we could use the 22px folders as previews? (similar to how [Folder Color does](http://2.bp.blogspot.com/-tblqIpef9RE/VHiMOmhXnhI/AAAAAAAAU8g/ExdKvg_0xdE/s1600/linuxmint171cajafoldercolor.png))

**Comment by wa4557** [comment]
That's totally fine, as I said it's probably quite easy to do that :)
Ok just to clarify: your mockup is still the way you want it to be? (With a larger preview icon probably)
And you'd like preview icons in the combobox-entry (22px) (I've no idea how easy it is to implement that :P)

**Comment by Foggalong** [comment]
\O/ yeah, still using mockup as a guide. Maybe 64px for the preview?

@costales any tips on how to implement the combobox previews?

**Comment by wa4557** [comment]
Ah I guess I found out how to do it (I love you stackoverflow:)
http://stackoverflow.com/questions/15807611/how-can-i-create-a-gtk-combobox-with-images-in-python

**Comment by Foggalong** [comment]
Awesome :D

**Comment by wa4557** [comment]
Yeah that's actually more work than expected :) I'll see what I can do in the next few days...

**Comment by Foggalong** [comment]
No problem! :)

**Comment by bil-elmoussaoui** [comment]
@wa4557 i might help if you need that ;) i will be for this weekend

**Comment by wa4557** [comment]
@bil-elmoussaoui Sure go ahead. The code is already more or less there just needs some restucturing :)

**Comment by wa4557** [comment]
@bil-elmoussaoui You still want to do this? If yes supercool, if not I might find some time this weekend :) It requires some work, but I guess mainly because I'm too stupid to understand the gtk packing procedure properly. 
Signals etc. (i.e. the hardest part) are already there

**Comment by bil-elmoussaoui** [comment]
Yes i still want to do this, i will start working on it tomorrow

2015-09-01 16:37 GMT+02:00 Andreas Angerer <notifications@github.com>:

**Comment by wa4557** [comment]
Top :+1:

**Comment by Foggalong** [comment]
:+1:

**Comment by bil-elmoussaoui** [comment]
Sorry guys i'm a little bit busy, i will try to do it this weekend if possible ;)

**Comment by Foggalong** [comment]
No problem! :)

**Comment by wa4557** [comment]
@bil-elmoussaoui Do you already have something? If not I might start working on this today. If yes and you have no time to finish/continue work on this you could give me what you have (pastebin) and I'll continue to work on this. Or if you really want to do this on your own I will let you do this and stop working on this

**Comment by bil-elmoussaoui** [comment]
@wa4557 I'm sorry, i started school this week and i'm so busy those days too :/ Just start working on it if you want to, if i got any free time i might help you with it ;)

**Comment by wa4557** [comment]
No need to apologize :) I'll start on this asap (argh so many things to fix here right now :)

**Comment by wa4557** [comment]
I have it ready, which means that it works, but I'm not able to center the widgets in the first and second row, help anyone? On a second note, please test it :)
https://github.com/wa4557/numix-folders/tree/gui2

**Comment by dirtydancing** [comment]
Looking good and working smoothly :+1: , status: https://github.com/wa4557/numix-folders/commit/2c7da2486a2d60ee8f94da3243b7b79b33beb1cd

I like the current design. For your consideration, a couple of thoughts:

1) Maybe left-align the style dropdown and the colour preview boxes? Or is everything centered?

2) Alternatively, maybe left-align all rows including the folder icon preview, except for cancel/apply?

3) Maybe use a bigger folder preview icon? Then again, iirc that would be much bigger and too big?

GUI screenshot:
![gui_new](https://cloud.githubusercontent.com/assets/7164227/9914375/f0892962-5cb1-11e5-9d22-ca24d362adeb.png)

**Comment by wa4557** [comment]
Aligning is extremeley complicated, frankly I have no idea how to do that properly :), but the idea is, that everything is centered. Left aligning somehow looks crooked, I tried that already. 

As to 3) The next size is 128px (twice as big) which is arguably too big

**Comment by wa4557** [comment]
Nevermind I've added a bigger preview (good call) because the next size is not 128px but 96px

**Comment by dirtydancing** [comment]
Yep, even better now :+1: 

Screenshot:
![gui_new_2](https://cloud.githubusercontent.com/assets/7164227/9916298/fb08f0ca-5cbb-11e5-98be-1c449d3c2685.png)

**Comment by wa4557** [comment]
I guess this is ready to be merged then. What is still buggy is the packaging though, but that's nothing I can contribute...

**Comment by palob** [comment]
Outstanding work @wa4557. Maybe include Cancel/Apply into the title bar using a ``GtkHeaderBar``?

**Comment by Foggalong** [comment]
AFAIK @PaoloRotolo is the only one with permissions to edit the packaging on Launchpad and he's been busy with school and work on Glucosio. I'll see what I can do though

**Comment by wa4557** [comment]
@palob Could you elaborate what you mean by that? I'm by no means an expert in gtk :)

**Comment by palob** [comment]
Something like [this](https://developer.gnome.org/hig/stable/figures/patterns/action-dialog.svg) or this:
![headerbar](https://cloud.githubusercontent.com/assets/7050624/9940568/ee1695ec-5d70-11e5-9cfe-6900f210ae9b.png)

But on a second thought maybe it's better not to make it look that GNOMEy.

**Comment by wa4557** [comment]
Looks fancy :) I've never seen something like this before, I guess for now I want to keep it the way it is...

**Comment by dirtydancing** [comment]
Do we know whether header bars are currently working for all other DE/shells besides GNOME shell?

**Comment by palob** [comment]
Header bars require GTK+ 3.10 or newer(Ubuntu 14.04 or newer) and may look out of place (or even like crap with the wrong theme) outside GNOME, that's the issue I see.

**Comment by dirtydancing** [comment]
I see. Well, in that case, I would also suggest to not go for the header bars at the moment, so as to keep things simple and to ensure maximum distro/DE compatibility. They do look sweet though :-)

**Comment by Foggalong** [comment]
Headerbars are sweet when done right, but some distros are only just getting support for them. As I understand it the DE the distro is running needs to a) use gtk 3.10+ & b) have header bar support enabled. Xubuntu only got them a release ago so I'm guessing slower distros like Debian might not have them yet.

**Comment by palob** [comment]
I don't know of anything like "headerbar support" and Debian Stable is on GTK 3.14 but speaking of which... what's the requirements for the current GUI?

**Comment by Foggalong** [comment]
Yeah, I think it's something the window manager developers need to allow for (i.e. xfwm enabled it with the last release of Xubuntu). I'm not sure on the requirements. @wa4557?

**Comment by wa4557** [comment]
I guess it should basically work with any 3.* gtk version since I've used only very basic functions. And python of course :)

**Comment by Foggalong** [comment]
With all the features having now been added I think we can close this issue, with the preview feature to be added later as per #118. Great work folks \O/

**Comment by PaoloRotolo** [comment]
Packaging fixed :)
Have fun!

**Comment by palob** [comment]
One thing just occured to me: How about widening the scope of the GUI to a general Numix GUI?
It could have buttons for downloading and installing the latest git version (in case there isn't a daily build package for your distro) applying the hardcode-fixer script.

Is this any close to a good idea?

**Comment by Foggalong** [comment]
@palob In theory a good idea yeah. I'd want that developed independently of the Folders GUI for now though since I'm not exactly sure how popular such an application would be
