### ISSUE TITLE
script doesn't work anymore

### ISSUE THREAD

**Issue by wa4557** [numixproject/numix-folders#106]
Something seems to have broken the script and I cannot find out what's causing it

```
„ln --help“ gives more information
ln: Unrecognized option -- o
```
And this multiple times (it seems that this happens everytime an icon is symlinked). I have no idea what's happening here

**Comment by bil-elmoussaoui** [comment]
I have an issue too 
`cp: cannot stat ‘styles/6\nblue\n42a5f5\n1976d2\n2a74b9/Numix-Circle/*’: No such file or directory`

**Comment by Foggalong** [comment]
@wa4557 didn't think we had symlinks in folders anymore?

@bli-elmoussaoui that's possibly something to do with the adding of "" in the shellcheck'd commit to escape troubling characters

**Comment by wa4557** [comment]
@Foggalong That's what I thought, and the reason I couldn't nail down the bug...

**Comment by wa4557** [comment]
Additionally something in the packaging also broke. the script in that is generated in `/usr/bin` is completely wrong (no linebreaks...)

**Comment by keevitaja** [comment]
I confirm, that fix by wa4557 will fix the issue!
