### ISSUE TITLE
Files app icon symbol size possibly too small in Curvy Design No. 5

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-folders#11]
In continuation of https://github.com/numixproject/numix-folders/issues/8, I am wondering: For Curvy Design No. 5 and its Files app icon, is the symbol a little smaller than usual on purpose? To me, this looks somewhat inconsistent with the other Numix-Circle icons. So far, I have not had this impression with the other Files app icon styles (i.e. Styles 3 and 6).

On the other hand, this might simply be a matter of getting used to it, but I thought nevertheless I would bring this to your attention.

Comparative screenshot of `file-manager.svg` for styles 1-6. As you can see, the folder symbol in Style No. 5 appears to be a little smaller than the others:

![file-manager_styles](https://cloud.githubusercontent.com/assets/7164227/6228810/a58a1194-b6b0-11e4-9221-5126be9f7d85.png)

Screenshot of Ubuntu 14.10 Unity launcher. The folder symbol size in the Nautilus/Files app icon (second from the top) to me appears to be somewhat small in this context:

![unity-launcher](https://cloud.githubusercontent.com/assets/7164227/6228822/d53afcbe-b6b0-11e4-8047-49a5d7824ef0.png)

**Comment by Foggalong** [comment]
Now you mention it it does look a bit smaller than the others. I can make it 1px bigger in every direction and that should fix it :)

**Comment by dirtydancing** [comment]
Thanks a lot, that was fast!

To confirm that with the newest version this issue as well as https://github.com/numixproject/numix-folders/issues/9 and https://github.com/numixproject/numix-folders/issues/10 have been fixed, here are two comparative screenshots of before and current (Ubuntu 14.10, default Ambiance GTK theme):

Before:
![numix-folders_curvy-design-5](https://cloud.githubusercontent.com/assets/7164227/6233336/622507ca-b6d2-11e4-9ab7-3d9c9e1844f2.png)

Current:
![numix-folders_curvy-design-5_2](https://cloud.githubusercontent.com/assets/7164227/6233357/7b0a0588-b6d2-11e4-9290-6b398f0cb911.png)

**Comment by Foggalong** [comment]
Issues always get fixed quicker if they happen to be in the project I'm working one :) Once I've finally finished the coloured variants for all styles this repo will go on the back burner again and I'll switch focus to updating Square & Circle.

**Comment by dirtydancing** [comment]
So it is good that you are presently working on the folders project :-) Curvy style No. 5 amazes me, and at the same time I appreciate the history/range of styles that you are covering with folder styles 1 to 6.
