### ISSUE TITLE
New Styles

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-folders#114]
There are 2 new styles I'd like to add to the folder switcher, but I'm a bit unsure as to whether they fit in or how they should be integrated.
- [**Numix uTouch**](https://github.com/numixproject/numix-icon-theme-utouch/tree/master/Numix-uTouch/scalable/places)
  On Jan 20th @IonicaBizau added a uTouch specific folder icon set. It feels only right that this should also be available in the switcher. It's gonna be a challenge to port though because the only size available is `/scalable`. This should probably be put between s5 and s6 since the latter was released on Jan 30th, but this puts a break in things continuity wise.
- ~~[**Ozon**](https://github.com/ozonos/ozon-icon-theme)~~
  This one is even more complicated. @cldx and @me4oslav have made a set of icons for the Ozon icon theme. Both are members of Numix so I thought it would be cool if the folders from there were also an option here. The names & colours are a bit different and the sizes aren't complete but I think that could be modified easily. It also uses a different symbol set which is a big pain.
  
  But the big complication comes from what style number to give it. The earliest commit is [Oct. 1st 2014](https://github.com/ozonos/ozon-icon-theme/commit/1a935d0527cbaa44c374cbfad0a9d8485915cd10?short_path=dfd43d0#diff-dfd43d069baffbb5a5f85a2325f11ef5) which I believe puts it inbetween s4 & s5. However I don't know if this makes things a bit disjoint being as they were developed separately along separate design guidelines.

Maybe these are both bad ideas but I thought I'd start a discussion so we could talk this out. @wa4557, @dirtydancing, @palob I'd love to hear your thoughts (along with anyone else who might be reading).

**Comment by IonicaBizau** [comment]
@Foggalong Thanks for :bell:. Shouldn't they be added in the [`styles`](https://github.com/numixproject/numix-folders/tree/1033a159cffcd2fe886776b54a3df06470c8e3d1/styles) directory?

**Comment by wa4557** [comment]
Does that mean that we have to design new sizes for uTouch? Or is it basically just scaling up and down (could be done automatically, probably). The same is true for the ozon folders (since they only exist as 16x16 and 48x48). Colouring should be fairly easy, if all the appropriate sizes are there :)

Concerning style numbers: no idea. Maybe change the numbering from dates to something like simplicity (number one for the "flattest" last number for the default style)? But I guess that's up to you

**Comment by dirtydancing** [comment]
General: I would recommend to officially announce Numix-Folders to the "general public", i.e. to all users. I am not sure if people are aware of all of this at all. Further update announcements could follow.

Numbering of the folder styles: I would recommend to simply number the styles along to when they are added to numix-folders, i.e. the next style added would be style 7, and so on. The Numix default style can have any style number (currently 6), and could be reset to default no matter which style number it has. And the respective description in the style overview (readme) could clarify the "history" of the styles.

**Comment by Foggalong** [comment]
@IonicaBizau 

No problem! And yeah that's where they'll be added :)

-----

@wa4557 

Yeah, both Ozon and uTouch will need new sizes designing. I did the same when fleshing out styles 3 and 5 since both were only original released in 1 or 2 sizes.

Numbering via flatness could get a bit complicated, and ambiguous in some situations too (e.g. comparing the uTouch style to the others).
 
-----

@dirtydancing 

I'd like the GUI to be finalised and the problem with it not working in the PPA version before it's officially announced. But trust me, it'll get there eventually :)

That numbering system is probably the easiest way to do it. We could also probably justify having uTouch as s7 since version 3 wasn't merged into master of uTouch until a few days ago. As this list gets bigger I'm also considering moving some of the README stuff (including the historical context descriptions) into the GitHub wiki. 

-----

@all 

I think I've more or less decided that the uTouch style should be included in some form, but my big quandary still is if Ozon is a good fit. It's closest in design to style 4 but also has the weird thing that the default colour is pink. This is going to make it look very out of place with the other 7.

What do people think? Is it distinct enough to be included or is the fact that it's part of another project a reason to keep it separate?

**Comment by palob** [comment]
I've always liked the Ozon folders and colours. Then again while I prefer the Ozon ones they're reeaaally similar to style 4 (which maybe could facilitate the porting).
Another thing to think about is whether to use the Ozon places symbols (a few additional ones there) or to use the symbols from style 4/6.

**Comment by dirtydancing** [comment]
As to the official announcement: sounds good! I probably just wanted to make sure that users can profit from the sweet `numix-folders` without the need to have additional folder styles finalised first :-)

Ozon: In the past, I have preferred the Ozon folders over Numix style 4, iirc the Ozon folders have more vertical height and are slightly different. So I would recommend to include Ozon as a separate style. I am not sure about the pink as default colour with regard to Numix GTK. Maybe the teal Ozon folder colour variant could serve as default colour for that style? Pink is one of the predefined folder colours anyways.

**Comment by Foggalong** [comment]
@dirtydancing ah yeah don't worry, this is a post announcement issue :)

**Comment by dirtydancing** [comment]
Ah, as to Ozon: Probably the default Ozon pink is different from the predefined pink? That would be an argument to have the Ozon defualt pink as the default colour for the Ozon folders. I am not sure here.

**Comment by wa4557** [comment]
I really like the uTouch icons, which means that I want them to be added. I'e already started this is what I am going to do:

1.) Simplify the icons (they are using masks etc., I guess this doesn't really work when using Qt @palob?)
2.) Add appropriate action icons, the ones already present in uTouch do not really fit in the existing theme
3.) There's a gradient in the current icons. I will keep that for the default ones, but for the other colours (and custom) I will remove that
4.) Different sizes of course :)

**Comment by dirtydancing** [comment]
@wa4557 Great :+1: 

As to the Ozon folder icons: after having given this some thought, I think that these should rather not be added. This is because they are quite similar to Numix style 4, and adding them might cause confusion.

**Comment by palob** [comment]
@wa4557 I've tested with Qt and the icons show up as broken as possible: a square for all ``actions`` and ``places`` icons. Just the colour is recognisable.

**Comment by Foggalong** [comment]
I'm gonna make the call not to have the Ozon folders. As others have said, they're a bit too similar to Style 4 and add more complications than the benefit of adding them.

**Comment by Foggalong** [comment]
The uTouch folders have seemingly since been lost to the sands of time. RIP uTouch folders, we hardly knew you :skull:
