### ISSUE TITLE
Missing symlink for folder-books

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-folders#122]
There's a missing symlink from `default-folder-books` to `folder-books`

**Comment by Foggalong** [comment]
It's not missing, it's just that an icon with that name has never been requested so presumably not used by anything. It came from a user suggestion like #78.

Regardless, symlinks are a numix-icon-theme issue :P

**Comment by bil-elmoussaoui** [comment]
My bad :P thanks! i will do the symlink in numix-icon-theme and create a pull request as i think i'm the only one who uses this icon

**Comment by Foggalong** [comment]
:+1:
