### ISSUE TITLE
Folders No Longer Changed

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-folders#125]
Prior to 8ffb7064086b2d9b9bdf6d308575a93f855dd480 some changed which has stopped the folder change working. I tested with a clean clone before pushing the PEP8 fixes and it didn't work then either, despite not giving any errors :(

**Comment by bil-elmoussaoui** [comment]
the lines i added must be before the import of 
`
 from gi.repository import Gtk, Gdk, GdkPixbuf, Pango		
`

**Comment by Foggalong** [comment]
The regression was introduced prior to that :/

**Comment by bil-elmoussaoui** [comment]
The version check should be before the import of Gtk! impossible to do that in an other way.. It's Gtk you can do nothing about it

**Comment by Foggalong** [comment]
I'M A DOPE. The problem was caused by not running the latest version of Numix base :P
