### ISSUE TITLE
gksu dependency

### ISSUE THREAD

**Issue by daltones** [numixproject/numix-folders#127]
I don't know if here is the best place to write this issue, but...

numix-folders script uses ```gksudo``` command. So, for debian-based system, it should include "gksu" as a dependency.

I think regular Ubuntu comes with gksu package bult in. But Ubuntu GNOME doesn't.

**Comment by Foggalong** [comment]
Thanks for bringing this to our attention :)

**Comment by dirtydancing** [comment]
Just for your information: the AUR package `numix-folders-git` includes a `gksu` dependency, and is working very smoothly with Arch/GNOME. Cf. https://aur.archlinux.org/packages/numix-folders-git/.

**Comment by PaoloRotolo** [comment]
Fixed in latest build (1.1.1).
Thank you!
