### ISSUE TITLE
Custom folders are not modified

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-folders#129]
Hello as i mentioned in #122 
I created the symlink in my local machine and when i used Numix folders to change the color/style from the default one to the style 5 color blue i had this result 
![screenshot from 2015-11-01 14-54-57](https://cloud.githubusercontent.com/assets/7660997/10869214/8a142324-80a8-11e5-8fd8-c6746305d6d7.png)

**Comment by bil-elmoussaoui** [comment]
CC: @wa4557

**Comment by wa4557** [comment]
Hmm, did you create the symlinks before you ran the script?

**Comment by bil-elmoussaoui** [comment]
Yes

**Comment by wa4557** [comment]
what does `ls -l folder-books.svg` give?

**Comment by wa4557** [comment]
There has to be somethinhg wrong with your symlinks. The actual Icon is rwplaced correctly

**Comment by bil-elmoussaoui** [comment]
```
ls -l folder-books.svg
-rw-r--r-- 1 bilal root 4853 nov.   1 15:14 folder-books.svg
```
I will do!

**Comment by wa4557** [comment]
Well that's not a symlink...

**Comment by bil-elmoussaoui** [comment]
@wa4557 Sorry i forgot to comment! i created the symlink now 
```bash
bilal@ideapad-u330:/usr/share/icons/Numix/48/places$ ls -l default-folder-books.svg
lrwxrwxrwx 1 bilal root 16 nov.   8 16:46 default-folder-books.svg -> folder-books.svg
```
and i still have the same result :(

**Comment by wa4557** [comment]
You have to do it with the default settings applied (that's important) and afterwards run the script...

**Comment by bil-elmoussaoui** [comment]
The same result

**Comment by wa4557** [comment]
It works for me!? Sure you didn't do anything wrong?
![unbenannt](https://cloud.githubusercontent.com/assets/6475757/11021197/33896f90-863a-11e5-9214-9ae6b48ffad3.png)

**Comment by bil-elmoussaoui** [comment]
you've created the symlinks in `/usr/share/icons/Numix`?

**Comment by wa4557** [comment]
Yeah

**Comment by wa4557** [comment]
@bil-elmoussaoui Any news on this?

**Comment by bil-elmoussaoui** [comment]
I just tried again with a fersh install of Numix & Numix folders and everything works fine! i guess a symlink in base would be fine ;)

**Comment by wa4557** [comment]
fancy creating a PR for that?

**Comment by bil-elmoussaoui** [comment]
Would really like to do that but my internet is really slow those days :(

**Comment by wa4557** [comment]
Ok I can do that :)
