### ISSUE TITLE
Numix Folders in Action

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-folders#13]
Hi, I would like to suggest to add some user screenshots of "Numix Folders in Action" (or whatever title you would prefer) to the numix-folders startpage.

Reason: My impression is that several users might not be aware of e.g. Curvy Folder Style No. 5, simply because that never went into production, or they might have seen only one folder icon and might have dismissed it from this incomplete impression. I am aware of e.g. this recent Numix Project post on Google+ relating to the different folder styles: https://plus.google.com/+NumixProjectOrg/posts/6P4KMDGZGQD but also this post is visually limited to a screenshot of the current numix-folders startpage with one example icon for each Numix folder style.

E.g., just yesterday I sent a screenshot of my desktop to a friend of mine who is also a Ubuntu & Numix user, and he switched to Curvy Folder Style No. 5 right away. Now, I would volunteer a screenshot of my actual desktop to get this going. This is Folder Style No. 5 on Ubuntu 14.10 with default Ambiance GTK theme and with default Ubuntu wallpaper (same as in 14.04 LTS), and since I figure that a lot of Numix users are using Ubuntu, they should be able to directly relate to this screenshot:

![ubuntu1410_numix-folders-5](https://cloud.githubusercontent.com/assets/7164227/6254433/d5d31e74-b7a8-11e4-8d7d-d5fa156a222b.png)

This is just an idea to make the folder styles options more approachable and to give users a more encompassing "in action" impression of the Numix folder styles. I would be delighted to hear what you make of this suggestion.

**Comment by Foggalong** [comment]
It's a nice idea, but a screenshot for every style (and then presumably every colour?) would massively increase the length of the README to the point where I'm not sure it would be fit for purpose. It's possible we could have links to screenshots of the themes in use elsewhere though. We'll be promoting the other styles too a bit more after this period of work is done

**Comment by bil-elmoussaoui** [comment]
Or just making a video(10 seconds of every style) ?

**Comment by Foggalong** [comment]
That would be even worse for fitting in a readme! :P

**Comment by dirtydancing** [comment]
Yeah, I see the point about overloading the README. A link to a screenshot collection or links to individual screenshots would serve the same purpose indeed. As to the different colours, point taken as well. Probably it would be a good idea to have the respective folder style default colour represented as a base line. A description of a screenshot might contain distribution, icon theme, folder style No. (colour).

A video is s.th. I have not considered so far, sweet idea, and I guess this would be in no way mutually exclusive to screenshots, so it would be rather an "and" than an "or" :-) What springs to my mind though is that with a video, this likely would tend to be a sort of "artificial" rundown of the folder styles (?). In contrast, the charm of screenshots from the user base would be that these would be settings that are actually "really" being used.

Good to hear also that Numix Project will be promoting the folder styles. numix-folders is a gem of a utility, and it should not remain a "hidden gem", even if hiding in plain sight :-)

**Comment by Foggalong** [comment]
There's little a video could add over a screenshot, so if we were to do this it would definitely be images we'd use. You'll have to convince me though that the screenshot has value over just the preview folder we have now

**Comment by dirtydancing** [comment]
Words may be less convincing here than the actual screenshots, but I will try anyways :-)

There is an aesthetic correlation between all the icons and there is an overall impression and composition of the desktop that is not revealed by the current isolated preview folder.

Take e.g. this comment from the Google+ post referred to above (I am not on Google+, so I could not reply over there, but I agree with the reply from Numix Project) https://plus.google.com/+NumixProjectOrg/posts/6P4KMDGZGQD "(...) 1 and 2 still my favorite. 5 and 6 is way to loud for the smooth, soft and balanced  theme,...﻿".

One reference to a screenshot also containing some current Numix(-Circle) icons, like the example screenshot above, would have made clear that, while still also a matter of personal preference, the vividness of the folder style No. 5 icons is matched by the vividness of the current apps icons. Or at least such a screenshot could have served as a simple and quick reference point for further discussion.

On the flip side, I would actually be curious to see an "in action" screenshot with Numix folder styles No. 1 and 2, simply to get an impression beyond one single preview folder.

So, with screenshots, users not only could make up their minds for their own use on a broader basis, but could also better appreciate the possible use cases for other folder styles.

**Comment by dirtydancing** [comment]
Actually, I just realised one more aspect as to why these screenshots are useful: the relevant point of visual reference. With the current preview folder overview, the exclusive points of visual reference are the other folder styles:

![numix-folders_styles](https://cloud.githubusercontent.com/assets/7164227/6270955/d35f9f7c-b85d-11e4-99b2-b96314234651.png)

But the relevant point of visual reference is the entire icon theme, and not the other folder styles.

For a user who is accustomed e.g. to folder style No. 2, it might be a big "leap of faith" to even consider e.g. folder style No. 5, esp. when these two styles are showing in the same overview. On the other hand, it might have an encouraging effect to have a corresponding "in action" screenshot available and to see that another user has already taken this "leap of faith" and is still living happily ever after. :-)

**Comment by Foggalong** [comment]
You've sold me on the idea :) If you'll oblige I have the two conditions:

   1. You take the screenshots. You can either submit them as a pull request (so you get credit) or email them to me at joshua.h.fogg@gmail.com

   2. Make them of the same style as [this one](https://github.com/numixproject/numix-folders/issues/13#issue-58114885), stock Ubuntu wallpaper, Numix HUD icon, Numix GTK (makes circle icons look better) and stock Numix icon themes (i.e. not old recycle bin)

**Comment by dirtydancing** [comment]
Great! Sounds all good to me. So I will go ahead and prepare the screenshots.

Alas, the first thing I noticed when I selected the Numix launcher_bfb icon was that apparently, the Numix logo on that has not yet been updated to the current "n" of the Numix logo (?). I will file a bug report against Numix-Circle about that, so that I can then take the screenshots with the updated icon.

**Comment by Foggalong** [comment]
Sorry, meant the Ubuntu Numix BFB icon not the Numix Numix one :P

**Comment by dirtydancing** [comment]
Ah, good, I see :-)
