### ISSUE TITLE
Add support for symbol-only smaller sizes ?

### ISSUE THREAD

**Issue by MrTimscampi** [numixproject/numix-folders#130]
I don't know if this should be filed here or in the regular Numix theme, but the special folder icons (Dropbox, Steam, Projects, etc) don't have the small symbol-only icons.
As a result, when viewing them in list form (for example in a GTK Open dialog), they look out of place.

**Example:**
![screenshot from 2015-11-18 10-23-26](https://cloud.githubusercontent.com/assets/1087450/11237162/6ead85a6-8dde-11e5-8b05-a8f7199a8b6f.png)

**Comment by Foggalong** [comment]
They do, just the way GTK currently handles custom folder icons means they're not properly displayed

**Comment by wa4557** [comment]
@MrTimscampi You can consider using nemo. They do a better job on this...

**Comment by MrTimscampi** [comment]
Thanks for the heads up, will try it :)  
Gnome is cool, but really weird in so many places...

**Comment by bil-elmoussaoui** [comment]
@MrTimscampi fixed on nautilus 3.18.4
![screenshot from 2016-01-10 23-04-12](https://cloud.githubusercontent.com/assets/7660997/12224357/8112992c-b7ee-11e5-92a7-67e15f4abf5f.png)

**Comment by Foggalong** [comment]
Nice to see Nautilus actually adding something for once rather than taking something away
