### ISSUE TITLE
not working in ApricityOS

### ISSUE THREAD

**Issue by Menidon** [numixproject/numix-folders#133]
the only thing that changes is the nautilus icon it gives me no errors anything i can do?

**Comment by bil-elmoussaoui** [comment]
@Menidon can you try to open Numix Folders from terminal using `numix-folders` and paste the output?

**Comment by Menidon** [comment]
well it opens the gui and if i apply it  get this
![screenshot from 2015-12-12 23-18-37](https://cloud.githubusercontent.com/assets/10180505/11764192/b531719e-a126-11e5-90aa-06507a1c7e7f.png)

**Comment by wa4557** [comment]
So why do you think it's not working?

**Comment by Menidon** [comment]
well because it isn't lol the folder icons don't change even if i reload the shell or restart completely.
like i said the only thing that changes is the nautilus icon.
![screenshot from 2015-12-12 23-21-57](https://cloud.githubusercontent.com/assets/10180505/11764210/7674f100-a127-11e5-98b8-adac96413929.png)

**Comment by wa4557** [comment]
Do you have  Numix installed in `/usr/share/icons` and in `~/.local/share/icons`? (i.e. do you have numix installed two times?)

**Comment by Menidon** [comment]
no i don't the default apricity icons are also numix circle though.

**Comment by wa4557** [comment]
Can you post a screenshot of `/usr/share/icons/Numix/48/places` after you've ran the script?

**Comment by bil-elmoussaoui** [comment]
@Menidon In your screenshot you don't have the same result as in mine.. 
```bash
gtk-update-icon-cache: Cache file created successfully.
gtk-update-icon-cache: Cache file created successfully.
Folder change complete!
```

**Comment by Menidon** [comment]
![screenshot from 2015-12-20 21-09-50](https://cloud.githubusercontent.com/assets/10180505/11919873/2c860a4c-a75e-11e5-9dec-1e3a05fcafa4.png)

**Comment by bil-elmoussaoui** [comment]
Try forcing updating the icon cache 
`sudo gtk-update-icon-cache -f /usr/share/icons/Numix/`

**Comment by Menidon** [comment]
hmmm well didn't work, but thanks anyway

**Comment by bil-elmoussaoui** [comment]
Is the OS you're using is based on Fedora or Debian? Anyway, try to remove the pre-installed theme and reinstall it again , using the Github repo to have the latest version for Numix-Circle. And try again. This might be an issue with Apricity OS.. or the way they've packaged Numix icons..

**Comment by Menidon** [comment]
it's Arch based, i'm not using the default icon theme.
doesn't matter anymore anyway need to reinstall OS anyway fucked something up with the update manager.

**Comment by Menidon** [comment]
other people in the ApricityOS forum have the same problem as me just to let you guys know.

**Comment by bil-elmoussaoui** [comment]
@dirtydancing As you're using Gnome too; is the distro you're using Arch based? 
@Menidon Well, that confirms my theory.. i think it's rather an issue with the OS. Once you've reinstalled your OS, please try again as i suggested and let us know

**Comment by dirtydancing** [comment]
Well, my distro is Arch-based in that it is Arch :) Yeah, using Arch/GNOME, numix-folders is running fine.

**Comment by Menidon** [comment]
@bil-elmoussaoui i will

**Comment by Menidon** [comment]
thanks again for the help guys

**Comment by palob** [comment]
The default icons used in Apricity OS is a modified theme based on outdated versions of Numix and Numix Circle (and other themes).
So you can't expect Numix Folders to work.

**Comment by Foggalong** [comment]
And update on this? If it is a bug with Apricity OS it'd be good to let them know

**Comment by Menidon** [comment]
@palob well but i'm not using the default theme

**Comment by dirtydancing** [comment]
@Menidon Is ApricityOS available as a final version, or is it still in beta? If still in beta, this might be why there are still these kinds of issues. Again, all is working very smoothly with Arch/GNOME.

**Comment by bil-elmoussaoui** [comment]
We should not really try to fix this. As ApricityOS is using a modified version of Numix theme;

**Comment by dirtydancing** [comment]
@bil-elmoussaoui As far as I understand this, this issue report is about using the original Numix icon theme, not the modified version of ApricityOS.

@Menidon Are you using numix-folders directly from git, or are you e.g. using the AUR package `numix-folders-git`? That AUR package has just recently been modified, cf. https://aur.archlinux.org/packages/numix-folders-git/.

**Comment by bil-elmoussaoui** [comment]
@Menidon try this `gsettings set org.gnome.desktop.interface icon-theme "Numix-Circle"`

**Comment by Foggalong** [comment]
I've emailed @agajews to see if we can't work out if this can be fixed

**Comment by Menidon** [comment]
@dirtydancing i'm using numix-folders-git  r391.a4e5ef2-1 i can't find any other version it's from the AUR.

**Comment by Menidon** [comment]
@bil-elmoussaoui i tried it, restarted the shell didn't work unfortunately.

**Comment by dirtydancing** [comment]
@Menidon As you are using the AUR package, at the same time this should mean that you are also using the AUR `numix-icon-theme-git` package, because that one is a dependency of the AUR `numix-folders-git` package. And exactly this combination is working with Arch/GNOME. Very strange.

**Comment by dirtydancing** [comment]
Apparently, there is no problem with Numix-Circle, as the Nautilus circle app icon is changing properly. For some reason, in contrast this does not work for Numix base, though. Even stranger :-)

**Comment by palob** [comment]
Is deleting Numix's icon cache file of any avail?

**Comment by dirtydancing** [comment]
Also, just like @bil-elmoussaoui when running numix-folders via Terminal with the `-t` flag, I get this output order, which looks like the proper order:
```
gtk-update-icon-cache: Cache file created successfully.
gtk-update-icon-cache: Cache file created successfully.
Folder change complete!
```

**Comment by Cauterize-Linux** [comment]
Hi, just wanted to update this thread. I tested this morning Numix-Folders on Apricity OS with both the Standard Numix and Numix-Circle Icons. Numix-Folders works great with both on Apricity OS. The only issue is when trying to use Numix-Folders with Apricity Icons. I provided a screenshot below of it working on my Apricity OS VM I use for testing.

![image](https://cloud.githubusercontent.com/assets/15967706/14770681/4dcf8a44-0a2c-11e6-9c9a-3ea6d4fa89f2.png)

Numix-Folders is meant to work with stock Numix icon sets. So I believe you can mark this bug closed since it is working as intended. Thanks for reaching out to Apricity OS.

**Comment by Foggalong** [comment]
Awesome, glad to hear this has been addressed! :)
