### ISSUE TITLE
Use ini file for configuration

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-folders#135]
Hello, 
I think it's a good idea to have a ini file for configuration instead of : 

```
6
blue
42a5f5
1976d2
2a74b9
```

Having this 

``` ini
[configurations]
style_number = 6
style_name = blue
first_colour = 42a5f5
second_colour = 1976d2
third_colour = 2a74b9
```

**Comment by bil-elmoussaoui** [comment]
@wa4557 We can use `ConfigParser` on this ;)

**Comment by wa4557** [comment]
I'm wondering if this is something necessary for such a "small" project?

**Comment by bil-elmoussaoui** [comment]
Could be helpful if we want to add a Save style button ?

**Comment by bil-elmoussaoui** [comment]
I suggest using gsettings for that, so i'm closing this
