### ISSUE TITLE
Icon blurry with ALT + TAB

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-folders#137]
In continuation of https://github.com/numixproject/numix-folders/issues/132#issuecomment-164195265 and https://github.com/numixproject/numix-folders/pull/136#issuecomment-168160381, the icon is still blurry with ALT + TAB.

Screenshot with Arch/GNOME (AUR package `numix-folders-git`):

![alt-tab](https://cloud.githubusercontent.com/assets/7164227/12067103/07f3ab14-aff4-11e5-9491-d76fe4ee5699.png)

**Comment by bil-elmoussaoui** [comment]
Can you open Gnome system monitor and see if it's detect  Numix folders or only Python3 ?

**Comment by dirtydancing** [comment]
I could not locate the process with GNOME system monitor at all.

htop shows `/usr/bin/python3 /usr/share/numix-folders/gui/...`

**Comment by dirtydancing** [comment]
Just in case that this is of relevance: to start, I simply entered `numix-folders` into the Terminal.

**Comment by bil-elmoussaoui** [comment]
Can you modify the python file as i did in my PR and try again?

**Comment by dirtydancing** [comment]
I checked your PR over from https://github.com/numixproject/numix-folders/pull/138, but unfortunately the icon is still blurry. Is this issue reproducible?

**Comment by bil-elmoussaoui** [comment]
Yep in Gnome 3.18 with Fedora. I think that i have an idea how to fix it but i won't have the time to do that now; maybe in a two/three weeks..

**Comment by dirtydancing** [comment]
Sounds fine to me. This is only a minor issue imo.

**Comment by wa4557** [comment]
@dirtydancing Not happening on Ubuntu icon is perfectly sharp. You sure you used the latest iteration with the new `.desktop` file?
![bildschirmfoto 2016-01-01 13 21 56](https://cloud.githubusercontent.com/assets/6475757/12070809/c88b818a-b08a-11e5-8de0-3ee91f74250f.png)

**Comment by dirtydancing** [comment]
Confirmed that the icon is indeed sharp after I copied the .desktop file to `local/share/applications` :+1:  Apparently for some reason the AUR package does not include the .desktop file, so I simply used the one directly from git. I figure this appears to be a case of having the .desktop file in place, be it in `local/share/applications` or in `usr/share/applications`?

@bil-elmoussaoui Can you confirm this situation for Fedora, as you are experiencing the same issue?

**Comment by wa4557** [comment]
The system tries to matches the current `WM_CLASS` to one that is defined in the `.desktop` files. If the `WM_CLASS` matches the icon defined in the `.desktop` file is used. That's the reason why @bil-elmoussaoui had to include the `StartupWMClass=` variable in the `.desktop` file :+1: Cool

**Comment by dirtydancing** [comment]
@wa4557 Are you installing numix-folders in Ubuntu via PPA? And is the .desktop file installed automatically via PPA? And if so, in what location?

**Comment by bil-elmoussaoui** [comment]
Works fine here! :+1:

**Comment by wa4557** [comment]
Using the PPA yes. The correct `.desktop` file is installed in `/usr/share/applications/`

**Comment by dirtydancing** [comment]
OK, thanks, I am closing this issue.

**Comment by dirtydancing** [comment]
Comment added to the AUR packager, cf. https://aur.archlinux.org/packages/numix-folders-git/#news

**Comment by dirtydancing** [comment]
Follow-up: AUR is working great now, including installing the .desktop file in `/usr/share/applications`.
