### ISSUE TITLE
How to use svgclean script on places icons

### ISSUE THREAD

**Issue by wa4557** [numixproject/numix-folders#139]
Since the `places` icons are the ones most prominentely using the `<clipPath>` tag, I was thinking about using the same procedure as on circle to get rid of them. The `svgclean` however cannot be used on them since it would remove the `replacecolour` variables that is used for the creating custom colours. 

@palob Do you happen to now which argument is responsible for that, [here](https://github.com/numixproject/numix-tools/blob/master/numix-tools/svgclean)? so that I can use the script without it?

**Comment by palob** [comment]
``--remove-fill-props`` might be the option in question (``svgcleaner-cli --help`` shows them all).

Is that ``replacecolour`` edited in by hand (or by script)?
Is it only used in the ``custom-*`` icons?
Are you sure ``svgclean`` touches the ``<clipPath>`` objects anyway?

**Comment by wa4557** [comment]
the `replacecolour` was actually edited by a script (Did not use an actual script but only cli magic). It would be however really hard to do it again, because if I run the script, colour1, colour2 and colour3 would be replaced by `#000` which makes it impossible to distinct them. 

Removing just the clipPath would be fine (using the `perl` regex) I just thought that while we're on it it would be cool to reduce the file size as well as much as possible...

**Comment by palob** [comment]
If ``svgclean`` still messes up after you've removed the options you could just take out the ``custom-*`` icons and run ``svgclean`` on the rest.

**Comment by wa4557** [comment]
I just thought about a better way: I just replace the the three replacecolours by some exotic colour first run the cleaning script afterwards and replace the colours back afterwards. Quite obvious actually...

**Comment by palob** [comment]
One more thing: Are you sure no icon actually uses clipping?
They mustn't in order to work flawlessly in Qt environments but in order to get rid of clipping you'd have to edit the icons manually.

**Comment by wa4557** [comment]
No they don't. I was thinking that maybe the shadows use clipping, but appearently this is not the case. Found a few miscoloured icons though :)
