### ISSUE TITLE
Default option is missing for the folder styles in the GUI

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-folders#141]
In the GUI, there is a `Default` option at the very top for the folder colours, but not for the folder styles.

I would suggest to add a `Default` option (currently style 6) at the very top of the styles as well, so the user can easily return to the Numix defaults and readily knows what they are.

![default](https://cloud.githubusercontent.com/assets/7164227/12074160/fdcb9672-b144-11e5-82ea-cbf39d913e73.png)

@bil-elmoussaoui

**Comment by wa4557** [comment]
That raises some questions however: 

1) What should the mini picture be? No picture at all or the current default one (that might look weird)?
2) Why exactly? I mean there are these mini pictures so you immediately see what the folders are going to look like
3) Would a "Reset" button be the better choice? (Next to the cancel button)

**Comment by dirtydancing** [comment]
My thougths:

1) No mini picture at all in the list (just like for the colours on the right hand side). Of course, the large preview folder in the center top would still show up. Also for the colours, the style 1-6 colours options appear in addition to the "Default" option, so having no mini picture on both sides would be consistent.

2) Because while there are mini pictures, there is no indication what the default style is. The default can be viewed as the Numix "recommendation", so having this as a distinct option makes sense imo.

3) An additional "Reset" button would be confusing imo. That is what the "Default" buttons (already present for the folder colours) are for. Moreover, "Reset" does not necessarily indicate "Default".

**Comment by wa4557** [comment]
1) Would do the same

2) Ok I see what you mean, I'll try to come upwith something. Needs a bit of code rewriting

3) Not a fan of a "Reset" (or "Default") button either

**Comment by dirtydancing** [comment]
:+1: How about this alternative: for the style selection, maybe rename `Style 6` into `Style 6 (Default)`?

One possible problem with that is that all the names have a kind of equal lenght currently.

Or maybe somehow mark `Style 6`, e.g. with bold font? Then again, that would not really be clear.

**Comment by wa4557** [comment]
Hmm. Actually the default button in the colours selection serves a different purpose than the new Default selector option in the style dropdown would serve. 

While the "Default" for the colours shows how each style would look like with the default colours,  whereas the new button is really nothing different than the selector for style 6. I actually like the idea of emphasizing somehow within the current selection that style 6 is the default one...

**Comment by dirtydancing** [comment]
Well, imo the purpose of a `Default` selection is the same for both style and colour: The `Default` selection for the colours shows indeed how each style would look with the respective's style default colour. And the suggested `Default` selection for the styles would show how the default style would look with the respectively selected colours.

E.g., already currently the `Default` colour selection coupled with the `Style 1` style is the same as the `Style 1` colour selection coupled with the `Style 1` style.

**Comment by bil-elmoussaoui** [comment]
Why not renaming Style 6 to default ?

**Comment by dirtydancing** [comment]
@wa4557 On the other hand, I see what you are saying :). So I figure the challenge here is to make this the least confusing possible while still indicating what the default style is.

**Comment by wa4557** [comment]
Exactly, but that's not the same imo. Because the "Default" button still does something different then for example the "Red" button. The new one would actually the exact same thing as button "Style 6"

The "Style 6 (Default)" does not work, because it corrupts the aligning completely. 
What about adding a small symbol near the default selector that shows that this style is the default one?
Either: https://github.com/numixproject/numix-icon-theme/blob/master/Numix/22/emblems/emblem-favorite.svg
Or this (I prefer that one):
https://github.com/numixproject/numix-icon-theme/blob/master/Numix/22/places/user-bookmarks.svg

**Comment by dirtydancing** [comment]
As a comparison, via the Terminal the user can just press `Enter` for the respective defaults and is done. But via the GUI with its visual component this can be different I figure, so there might be no need for consistent `Default` selection choices at the top of both style and colour.

So I also tend to prefer the approach with indicating Style 6 as the default style. One possible problem with those kinds of emblems is that they might be misunderstood as a personal preference, or as the last personally selected style choice. So e.g. how about a mini-Numix-logo? :) As the text is left-aligned, this logo might follow after the `6` of `Style 6` and hopefully not corrupt the aligning.

I am not convinced of renaming `Style 6` to `Default`, as e.g. the default style number might change, so the default indication should be as flexible as possible. Also, e.g. the colour selection includes `Default` as well as `Style 6`, so imo the style selection should also contain `Style 6`.

**Comment by dirtydancing** [comment]
Or maybe just a simple asterisk `*` next to `Style 6` to indicate the default, no need for a special icon?

**Comment by wa4557** [comment]
Yeah the icon would work but slightly breaks the whole aligning - but would be doable. 
The asterisk idea:
![bildschirmfoto 2016-01-02 15 17 23](https://cloud.githubusercontent.com/assets/6475757/12074728/fdf23a42-b163-11e5-848c-38e51e109cd0.png)
![bildschirmfoto 2016-01-02 15 16 40](https://cloud.githubusercontent.com/assets/6475757/12074729/011456ce-b164-11e5-93ce-5c39d5e426b0.png)

**Comment by dirtydancing** [comment]
I have a lot of sympathy for the asterisk, simple and effective imo.

**Comment by wa4557** [comment]
Me too. Let's see what others say :+1:

**Comment by Foggalong** [comment]
I can go with the * yeah :) is it the possible to have the * dynamically added based on which style style 0 links to?

**Comment by wa4557** [comment]
Yeah, that's the way it is supposed to be. The asterisk goes where the default option is. For now it is style 6 but can be changed easily.

**Comment by Foggalong** [comment]
:+1:

**Comment by bil-elmoussaoui** [comment]
This one can be closed :p
