### ISSUE TITLE
Bookmarks won't retain folder colour

### ISSUE THREAD

**Issue by airatin** [numixproject/numix-folders#147]
Hi,

Whenever I reboot Cinnamon or start Linux (Mint, 17.3), the folder colours won't appear in the bookmarks. However, they do appear once I click on that folder in Nemo. It would be nice if they appeared in the bookmarks right when I start the system, without having to click on them (or open a Nemo file directory to where these folders are located). Maybe I'm not explaining it well, so please see attached pictures (I added 2 custom colours of my own, in case you're wondering where those are from).

When I start up the system:
![before](https://cloud.githubusercontent.com/assets/16682521/12290840/e34047d8-b9b1-11e5-9e82-b2bebb76b5b4.png)

After I open the file directory where the bookmarks (folders) are located, or click on them individually:
![after](https://cloud.githubusercontent.com/assets/16682521/12290832/db8ad8aa-b9b1-11e5-9f98-1c550ecacdce.png)

**Comment by bil-elmoussaoui** [comment]
Not a Numix icon theme issue, report that to https://bugs.launchpad.net/folder-color

**Comment by airatin** [comment]
OK, done and done.
