### ISSUE TITLE
Does not work with Antergos Arch Linux

### ISSUE THREAD

**Issue by GLTR87** [numixproject/numix-folders#148]
I get the following message when running numix-folders (on two computers with Gnome and Cinnamon if that changes anything):

gtk-update-icon-cache: Cache file created successfully.
gtk-update-icon-cache: Cache file created successfully.
gtk-update-icon-cache: The generated cache was invalid.
Folder change complete!

The following packages are installed from the AUR:
numix-circle-icon-theme-git 0.r2693.e849d05-1
numix-folders-git r395.f2f230b-1
numix-icon-theme-git 0.r1267.4430227-1

I know there can be issues with icons containing spaces, but I couldn't find any in both Numix and Numix-Circle folders.
It works fine in Ubuntu using the Numix PPA.

Thanks for any help!

**Comment by dirtydancing** [comment]
I can not confirm this with Arch/GNOME and the same AUR packages, all running smoothly at my end. Are you sure that your AUR packages are up-to-date?

Via Terminal I get this:
```
gtk-update-icon-cache: Cache file created successfully.
gtk-update-icon-cache: Cache file created successfully.
Folder change complete!
```

**Comment by GLTR87** [comment]
I'm pretty sure my AUR packages are up to date (I run yaourt -Syua frequently).
Anyway, I've removed all the numix packages, deleted the leftover files and reinstalled them.
It works! I still have the same error message, but my folders are now blue.

**Comment by dirtydancing** [comment]
I see. Just in case: `yaourt -Syua` will not get you the latest git version unless the AUR package itself has been updated. To get the latest git version you will need to add the `--devel` flag, so you run `yaourt -Syua --devel` and maybe also `--noconfirm`, and of course you need to know what you are doing :-)

E.g., I currently have
```
aur/numix-circle-icon-theme-git 0.r1677.fe74d83-1 [installed: 0.r2926.e7008b4-1]
aur/numix-folders-git r385.9249679-1 [installed: r396.d21060a-1]
aur/numix-icon-theme-git 0.r317.290d12e-1 [installed: 0.r1695.a704451-1]
```

It is still strange that you are getting the error message. I can not confirm this with Arch/GNOME. There should not be 3x icon cache updates anyways, only 2x relating to Numix base and to Numix-Circle.

**Comment by GLTR87** [comment]
Thanks, I did not know about the --devel flag.
I now have the same numix versions as you.
The error message still appears, but the script works and the folders change.

**Comment by dirtydancing** [comment]
:+1:

Well, I figure as long as everything works, this should be just fine. Maybe s.th. specific to Antergos.

**Comment by dirtydancing** [comment]
@wa4557 
@bil-elmoussaoui 

Just in case: Any ideas why @GLTR87 is getting 3x icon cache updates with the last one failing? Cf. comment above: https://github.com/numixproject/numix-folders/issues/148?_pjax=%23js-repo-pjax-container#issue-127752547. With Arch/GNOME, I get 2x icon cache updates and all is fine.

Looking at the script, maybe this is related to Numix-Square? @GLTR87 Do you happen to have Numix-Square installed?

**Comment by dirtydancing** [comment]
Ah, isn't Antergos using Numix-Square as default icon theme? This might be the reason behind this.

**Comment by wa4557** [comment]
@dirtydancing yeah most definitely square still has those icons with spaces in the name

**Comment by dirtydancing** [comment]
@wa4557 Thanks!

@Foggalong Issue filed against Numix-Square, https://github.com/numixproject/numix-icon-theme-square/issues/20.

**Comment by GLTR87** [comment]
@dirtydancing 
Good thinking, thanks!
Numix-Square is installed (I use Circle).
The new folder colors do work with Numix-Square, even with the error message.
Removing Numix-Square makes the error message disappear.
The following Icons have spaces in Numix-Square/48x48/apps/:
56B4_Battle.net Launcher.0.svg
5C12_World of Warcraft Launcher.0.svg
Yahoo Mail-mail.yahoo.com.svg
