### ISSUE TITLE
CLI script

### ISSUE THREAD

**Issue by bharadwaj-raju** [numixproject/numix-folders#151]
While the PyGTK <s>script</s> app is nice and all, it would be good to have a CLI version for scripting (and we Linux users like the terminal).

**Comment by Foggalong** [comment]
You clearly didn't look very far :P 
![screenshot_2016-02-16_16-41-11](https://cloud.githubusercontent.com/assets/5920259/13083257/20183e60-d4cc-11e5-964e-3c329a6edc94.png)

**Comment by bharadwaj-raju** [comment]
Sorry.

**Comment by Foggalong** [comment]
No problem! Let us know if you have any more problems :)

**Comment by bharadwaj-raju** [comment]
Does this work for KDE? (The KDE Numix icon theme)

**Comment by Foggalong** [comment]
It should do yeah. The KDE numix icon theme is just the same - we believe in using one icon theme for all DEs :)
