### ISSUE TITLE
problem with case conversion?

### ISSUE THREAD

**Issue by jamdox** [numixproject/numix-folders#152]
Was getting "Oops...colour" error.  Might have fixed it by commenting out line 159 of numix-folders script.

Zsh.

**Comment by wa4557** [comment]
Cannot reproduce this. What did you type in as colour when asked?

**Comment by jamdox** [comment]
`blue`

**Comment by wa4557** [comment]
still not reproducible for me. When running `numix-folders` with `zsh``and selecting `blue` everything works fine

What does `echo "$(tr '[:upper:]' '[:lower:]' <<< "blue")"` give you?

**Comment by Foggalong** [comment]
Closing since without more information we can't fix it :(
