### ISSUE TITLE
Remove Preview Background

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-folders#153]
In the previews for the README the folder previews have a white background which should be transparent.

**Comment by wa4557** [comment]
When looking at the files (preview.png) there is no white background. Has to do something with how github handes png files

**Comment by bil-elmoussaoui** [comment]
Can confirm what @wa4557 said! Just downloaded the preview files and they look transparent
![capture du 2016-11-05 20-39-22](https://cloud.githubusercontent.com/assets/7660997/20033048/f77eedd2-a397-11e6-83ba-178f3d28b158.png)

**Comment by Foggalong** [comment]
Damn :(
