### ISSUE TITLE
Icons for Ubuntu Software

### ISSUE THREAD

**Issue by irondave** [numixproject/numix-folders#154]
Missing icons for ubuntu software ( Ubuntu 16.04).
Thank you.

**Comment by Foggalong** [comment]
I'm not sure what it is you're asking for? Please provide more information (screenshots, etc)

**Comment by denyardy** [comment]
this screenshot for ubuntu software
![screenshot from 2016-05-12 16-47-31](https://cloud.githubusercontent.com/assets/19324157/15210605/6415cf00-1861-11e6-8d87-76307639d72a.png)
