### ISSUE TITLE
numix-folders not available for Ubuntu 16.04 trough PPA

### ISSUE THREAD

**Issue by 1Claude** [numixproject/numix-folders#156]
Do you plan on making it available for Ubuntu 16.04 ?

Terminal says it can't find the package : numix-folders

**Comment by Foggalong** [comment]
CC @PaoloRotolo

**Comment by 1Claude** [comment]
I must say that I downloaded the zip file and that it works. But it used to be available though the PPA.

**Comment by Foggalong** [comment]
Yeah, it's just that the builds haven't been triggered for 16.04 yet :)

**Comment by morph027** [comment]
Just in case you are having your own repo ;)

```bash
mkdir /tmp/docker
docker run --rm -it -v /tmp/docker:/build -w /build ubuntu:xenial /bin/bash

apt-get update
apt-get install git-core devscripts debhelper -y
git clone https://github.com/numixproject/numix-folders
git clone -b packaging https://github.com/numixproject/numix-folders packaging
mv packaging/debian numix-folders/
cd numix-folders/
cat > changelog << EOF
numix-folders (1.1.1+201608030232~194~ubuntu16.04.1) xenial; urgency=low

  * Add gksu dependency.

 -- Paolo Rotolo <paolorotolo@ubuntu.com>  Thu, 12 Jan 2016 21:30:18 +0100
EOF
cat debian/changelog >> changelog

debuild -us -uc << EOF
y
EOF
```

Now you should have ```numix-folders_1.1.1+201608030232~194~ubuntu16.04.1_all.deb``` inside ```/tmp/docker```.

**Comment by paolorotolo** [comment]
Okay, the package is building for Xenial, Yakkety and Zesty right now :)
https://code.launchpad.net/~paolorotolo/+recipe/numix-folders

**Comment by Foggalong** [comment]
@paolorotolo Thanks Paolo! Will these rebuild automatically when we push updates or do we need to trigger a new package build manually?

**Comment by paolorotolo** [comment]
Yeah, it will build automatically.

**Comment by Foggalong** [comment]
Awesome, thanks :grinning:
