### ISSUE TITLE
Visual inconsistency with folder colours pink and purple in style 5

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-folders#16]
This issue may be rather a subjective impression than an objective issue, but this caught my attention, and as right now is the proper time to address this, I am filing this report. Please feel free to close this.

When going through the different folder colours in Curvy Design No. 5, the pink and purple colours caught my attention. The folders in these colours look somewhat "flatter" than in the other colours. I realised that this seems to be because of the colour of the upper edge in the background.

Screenshot of the default-folder, size 48x48:

![default-folder](https://cloud.githubusercontent.com/assets/7164227/6459863/fa462032-c192-11e4-8f2b-c3aa3737e1e5.png)

For default-folder, the marked upper edge in the background is visible "darker" or "further away" than the main folder colour in the front.

In contrast, screenshots of pink-folder and purple-folder, size 48x48:

![pink-folder](https://cloud.githubusercontent.com/assets/7164227/6459890/386be1c6-c193-11e4-9804-62d60553772c.png)
![purple-folder](https://cloud.githubusercontent.com/assets/7164227/6459891/3abfcc26-c193-11e4-8880-c576990da51a.png)

In both these cases, the colour in the background is almost the same as in the front. For purple, it looks just a nuance darker, for pink it even looks a nuance lighter.

This takes away some "depth" and even evokes the impression that the entire folder front is flat, and that the darker part is only a kind of curvy print on the surface, not actually the backside of the folder further in the background. But that would be inconsistent with the "depth" of the overall folder design.

To illustrate further, here is a screenshot of pink-folder-open:

![pink-folder-open](https://cloud.githubusercontent.com/assets/7164227/6460291/336cf3d8-c196-11e4-95f5-63bcee416af2.png)

The upper edge looks almost like it is closer to the observer than the front, which is visually misleading.

As a comparison, screenshot of default-folder-open (all fine):

![default-folder-open](https://cloud.githubusercontent.com/assets/7164227/6460296/3e63f732-c196-11e4-8dbe-d1694edb21a2.png)

I only had this impression with the folder colours pink and purple, all the other colours looked fine to me.

Finally, for a direct comparison and for verification, screenshot overview with all 10 folder colours:

![folder-overview](https://cloud.githubusercontent.com/assets/7164227/6460758/5cb91826-c19a-11e4-9663-dd6df0ffc274.png)

**Comment by Lumpenhund** [comment]
Hello,

I really like Numix and it's folder icons, especially No. 5. :-)
Because of that I look at them in more detail, and I can confirm dirtydancing's observations.

greetings
Lumpenhund

**Comment by wa4557** [comment]
@dirtydancing Is this bug still valid? I think since all the different colours are designed the same way it is not reasonable to change the design only for pink and purple. A possible way to fix this would be to use different colours for pink and purple, but this is now possible when using the `custom` option

**Comment by dirtydancing** [comment]
Agreed. Style 5 is somewhat of an exception for the colour contrast with pink and purple (and also for a couple of other colours), and changing these colours would lead to inconsistencies with the predefined colours as laid out in the Readme.

And indeed, this can be addressed with custom colours (at least for the default folders), cf. also this other comment of mine with comparative screenshots: https://github.com/numixproject/numix-folders/pull/63#issuecomment-100448946.

Closing this issue.
