### ISSUE TITLE
wayland support

### ISSUE THREAD

**Issue by jamdox** [numixproject/numix-folders#162]
it'd be nice to be able to use the GUI under wayland session in gnome!

**Comment by bil-elmoussaoui** [comment]
Can you open the gui under wayland and paste the error messages you have
got ?

**Comment by matheusvsilva** [comment]
Hi, i had this error:

No protocol specified
Unable to init server: Could not connect: Connection refused
No protocol specified
Unable to init server: Could not connect: Connection refused
No protocol specified
Unable to init server: Could not connect: Connection refused

(numix-folders:25143): Gtk-WARNING **: cannot open display: :0

**Comment by MrTimscampi** [comment]
Same issue on Fedora 25 Beta (which has Wayland as default)

**Comment by bil-elmoussaoui** [comment]
@Foggalong One of the main issues on wayland is that you can run gksudo anymore...Do you have any idea how to avoid that? or something else we can use ?

**Comment by Foggalong** [comment]
@bil-elmoussaoui Basically no. gksu has been deprecated but nothing function has yet replaced it :/

**Comment by bil-elmoussaoui** [comment]
I think we can use `pkexec` and ship our own PolicyKit (should be placed on `/usr/share/polkit-1/actions/`). Even synaptic moved to use pkexec instead of gksudo...

**Comment by Foggalong** [comment]
Last I heard pkexec wasn't ready for daily use yet, though admittedly it's a very long time since I looked into it. I'm happy to make the switch but it'll be a few days until I have time to sit down and learn how it works, so if you or someone else wants to do that in the mean time then be my guest :)

**Comment by bil-elmoussaoui** [comment]
I will do by this evening

**Comment by palob** [comment]
Couldn't we alternatively implement the script on a per-user base by copying the icons to ``~/.local/share/icons/``? What's in local directories is priotitised over ``/usr(/local)/share``. This way we wouldn't need to ask for root user priviliges and the customised icons would persist updates of a global Numix installation, addressing #101.

**Comment by bil-elmoussaoui** [comment]
I'm going to work on improve Numix folders and i wanted to do the same as you're proposing ;) hope it will work without any problem ;)

**Comment by Foggalong** [comment]
That sounds like a better way to do things :)
