### ISSUE TITLE
Folder Color Custom and Global options

### ISSUE THREAD

**Issue by tsutsarin** [numixproject/numix-folders#163]
I installed Folder Color:
http://foldercolor.tuxfamily.org/

But for Numix icon theme there's no option to select Custom color and apply color as Global to all folders.
Only default colors are present: Blue, Brown, etc

How do I enable this options?

OS: Ubuntu 16.04

**Comment by Foggalong** [comment]
CC: @costales

**Comment by costales** [comment]
Yes @Foggalong You wanted [that](https://github.com/numixproject/numix-folders/issues/51#issuecomment-96742178
) :) We agreed to add those options as [opt-in feature on themes](https://github.com/numixproject/numix-folders/issues/51#issuecomment-97146503
).

@tsutsarin You need to create a file with this name in any resolution, for example:
```
costales@dev:~$ find /usr -name "folder_color_globalcolor.svg"
/usr/share/icons/hicolor/16x16/actions/folder_color_globalcolor.svg
costales@dev:~$ 
```

A hug!

**Comment by Foggalong** [comment]
@costales Oh right, I misunderstood what problem the user was having!

@tsutsarin Global colour switching needs to be done via the script provided in this repo. It can be done using other things but the this is the only way you'll get it consistent for non-place icons (e.g. apps)
