### ISSUE TITLE
Custom color

### ISSUE THREAD

**Issue by tsutsarin** [numixproject/numix-folders#164]
Is there any possibility to provide custom color hexes?

The README says nothing about it, but there's "custom" item in colors table, so I thought there might be some option or perhaps workaround.

**Comment by wa4557** [comment]
It would be a good idea to just run the script (i.e.`./numix-folders`)? You'll see that it's possible, and also pretty intuitive to use.

**Comment by tsutsarin** [comment]
Oh, it really has that option! I was inattentive, thank you!
