### ISSUE TITLE
numix-folders not change color folders

### ISSUE THREAD

**Issue by Faust30000** [numixproject/numix-folders#174]
In the last update 1.1.1+201704051617~198~ubuntu16.04.1, the program does not change the color of the folders and, at startup, does not require a root access. If you run as administrator from the terminal, it also does not change the color of the folders.
Linux Mint 18.1 Cinnamon.

**Comment by theoneandonly-vector** [comment]
same problem on arch

**Comment by wa4557** [comment]
@bil-elmoussaoui do you have to look into that? I guess this is related to gksu somehow...

**Comment by bil-elmoussaoui** [comment]
@wa4557 I was thinking about refactoring the app a little bit and use pyexec instead of gksu

**Comment by wa4557** [comment]
Yeah makes sense. Is pkexec already working as a replacement for gksudo?

**Comment by bil-elmoussaoui** [comment]
Yep, works on every distro out there. I will try to work on it this weekend

**Comment by palob** [comment]
Do we need this at all? Applying the folder changes on a per-user base will make the changes persist numix-icon-theme updates.

**Comment by wa4557** [comment]
But then you have the problem that icon lookup is broken again, if icons appear with the same name in both icon themes (even if the names are only similar). This is the issue we had with circle / base status icons

**Comment by palob** [comment]
No, everything what is found in ``$HOME`` will be prioritised.

**Comment by Foggalong** [comment]
pkexec now is used!
