### ISSUE TITLE
GUI not opening

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-folders#178]
On KDE Neon 5.11 CLI works fine but running sudo ./numix-folders gives this error

`Traceback (most recent call last):
  File "/usr/share/icons/Numix/gui/gui", line 16, in <module>
    require_version('Notify', '0.7')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 102, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Notify not available`

Is there a way to resolve this issue?

**Comment by palob** [comment]
Are you running the Wayland session?

**Comment by arasbill** [comment]
No. i am running X11.

**Comment by Presmanes3** [comment]
Same problem here, I am using Debian 9 Unstable with KDE 5.13.5 and also running in X11

Do you have any solution for the problem?

**Comment by palob** [comment]
For now you can use the CLI with the -t option.
