### ISSUE TITLE
numix-folders not available in PPA for Ubuntu 17.10

### ISSUE THREAD

**Issue by PureRumble** [numixproject/numix-folders#179]
Hi

numix-folders isn't available in the PPA for Ubuntu 17.10. Is it because it doesn't support Ubuntu 17.10 or Wayland or did you just miss it?

Kind regards, Arash

**Comment by palob** [comment]
Hi, I think that's a packaging issue foremost but the GUI doesn't un on Wyland yet.

**Comment by Foggalong** [comment]
This should now be fixed! :smile:
