### ISSUE TITLE
Simply does not work on KDE Plasma for a long while now.

### ISSUE THREAD

**Issue by freefreeno** [numixproject/numix-folders#183]
I left this same problem in aur in March and now I downloaded everything again this morning and I still have the same problems.
First off there was a launcher when I used to use XfCE and in KDE there is no application launcher in Kickoff menu.
So I go to the folder and run the script and get this error .
Traceback (most recent call last):
  File "/usr/share/numix-folders/gui/gui", line 14, in <module>
    from gi import require_version
ImportError: cannot import name 'require_version' from 'gi' (unknown location)

I installed all my files from Arch aur and this has been this way since I know March.

**Comment by Foggalong** [comment]
That would be because the GUI interface is a GTK application and thus has dependencies that needs to be met. This either means:

1. The person packaging it for the AUR hasn't flagged all the needed dependencies so they've not been installed, and you didn't have them otherwise because they're not part of default Plasma. 
2. There's a bug in our application with KDE systems where, even if they are installed, the dependencies aren't being detected.

It'd be nice to be able to confirm that it's not 1 before we start debugging for 2. Can you confirm whether GTK is installed on your system, and if so what version?

**Comment by freefreeno** [comment]
I have GTk2, GTK3  , GTk engines, GTk engine murrine ,gnome themes extra, GTKmm, GTKspell, and more I use GTk apps with NO PROBLEMS
I use Arch so my stuff is the Newest in the stable branch. I am pretty sure if not positive it is a problem on your end.

**Comment by freefreeno** [comment]
[josh@archkde ~]$ sudo pacman -Si gtk2
Repository      : extra
Name            : gtk2
Version         : 2.24.32-1
Description     : GObject-based multi-platform GUI toolkit (legacy)
Architecture    : x86_64
URL             : https://www.gtk.org/
Licenses        : LGPL
Groups          : None
Provides        : None
Depends On      : atk  pango  libxcursor  libxinerama  libxrandr  libxi  libxcomposite
                  libxdamage  shared-mime-info  cairo  libcups  gtk-update-icon-cache
                  librsvg  desktop-file-utils
Optional Deps   : gnome-themes-standard: Default widget theme
                  adwaita-icon-theme: Default icon theme
Conflicts With  : None
Replaces        : None
Download Size   : 5.15 MiB
Installed Size  : 34.18 MiB
Packager        : Jan Alexander Steffens (heftig) <jan.steffens@gmail.com>
Build Date      : Mon 08 Jan 2018 08:56:04 PM CST
Validated By    : MD5 Sum  SHA-256 Sum  Signature

[josh@archkde ~]$ sudo pacman -Si gtk3
Repository      : extra
Name            : gtk3
Version         : 1:3.24.8-1
Description     : GObject-based multi-platform GUI toolkit
Architecture    : x86_64
URL             : https://www.gtk.org/
Licenses        : LGPL
Groups          : None
Provides        : gtk3-print-backends
Depends On      : atk  cairo  libxcursor  libxinerama  libxrandr  libxi  libepoxy
                  gdk-pixbuf2  dconf  libxcomposite  libxdamage  pango  shared-mime-info
                  at-spi2-atk  wayland  libxkbcommon  adwaita-icon-theme  json-glib
                  librsvg  wayland-protocols  desktop-file-utils  mesa  cantarell-fonts
                  colord  rest  libcups  libcanberra  fribidi  gtk-update-icon-cache
Optional Deps   : None
Conflicts With  : gtk3-print-backends
Replaces        : gtk3-print-backends<=3.22.26-1
Download Size   : 10.69 MiB
Installed Size  : 73.21 MiB
Packager        : Jan Alexander Steffens (heftig) <jan.steffens@gmail.com>
Build Date      : Wed 10 Apr 2019 06:12:48 PM CDT
Validated By    : MD5 Sum  SHA-256 Sum  Signature

Here is all my applications with GTK in title.
gtk2                   gtk-engines            gtk-update-icon-cache
gtk3                   gtkmm                   gtk-engine-murrine

**Comment by palob** [comment]
I'd recommend to use the CLI via the ``-t`` option.

**Comment by Foggalong** [comment]
@freefreeno Thanks for so thoroughly debunking option 1, will have a look to see if we can resolve option 2. In the mean time, as @palob says, I'd recommend using the CLI interface.

**Comment by freefreeno** [comment]
I will give it a shot and report back. The guy packaging the AUR repo does know what he is doing for sure by the way. It is the maker of all 10 desktops of  Arcolinux.

**Comment by freefreeno** [comment]
I haven't tried with -t option yet but same error without -t option in CLI for sure.

**Comment by Foggalong** [comment]
Closing this due to lack of follow up from original reporter. If someone else runs into this problem will happily reopen
