### ISSUE TITLE
 numix-folders PPA not available for Ubuntu versions 17.10 to 19.04

### ISSUE THREAD

**Issue by merfire** [numixproject/numix-folders#184]
Can we get numix-folders in PPA for Ubuntu versions 17.10 to 19.04?
Currently it says: Unable to locate package numix-folders,
if you run:
sudo apt-get install numix-folders

**Comment by Foggalong** [comment]
@khurshid-alam Can we get the PPA pull for these fixed :)

**Comment by khurshid-alam** [comment]
I will take a look.

**Comment by khurshid-alam** [comment]
It is fixed now (had to fix bzr packaging repo version). Note, Ubuntu 18.10 reached eol, so I won't be updating that.
