### ISSUE TITLE
numix-folders cannot be installed due to gksu dependency in Ubuntu 18.04

### ISSUE THREAD

**Issue by Vicat28** [numixproject/numix-folders#185]
gksu package has been removed from Ubuntu's repo in version 18.04 - it was replaced by pkexec.
As a result, numix-folders fails to install from the PPA because of the unmet dependency.
I would suggest switching to pkexec in numix-folders.

**Comment by palob** [comment]
Sorry for this, has been on our list for a long time. See #178 and #162.

**Comment by Alby407** [comment]
Is there a fix for the dependency problem?

**Comment by Alby407** [comment]
> Is there a fix for the dependency problem?

Ah, I just saw that the script also has a `-t` option for terminal usage! My Bad!

**Comment by Hebgbs** [comment]
> Is there a fix for the dependency problem?

For Ubuntu, anyway, install `libgtop`, `libgksu` and `gksu` for Xenial from UPS. _This isn't a solution._ This app should be using `pkexec` instead.

**Comment by gilbertohasnofb** [comment]
Now that this issue has been fixed, are there any plans to update the package version available through your official PPA?

**Comment by cristiadu** [comment]
> Now that this issue has been fixed, are there any plans to update the package version available through your official PPA?

+1, still having this issue on the latest PPA

**Comment by Hebgbs** [comment]
I know this comment is closed but on Arch the problem doesn't exist. gksu is listed as an optional dependency but it seems like the AUR is able to build the software so it runs without gksu.
