### ISSUE TITLE
Remove the default colour images.

### ISSUE THREAD

**Issue by Hebgbs** [numixproject/numix-folders#187]
There isn't a reason to bloat the application with images for default colour selections. In my testing, at least on Ubuntu 19.04 (after transplanting obsoleted deps from three years ago) the app's custom routine works just fine, and the application would be _way_ simplified if it did _only_ the custom routine with the other colour options just being custom presets instead.

**Comment by Foggalong** [comment]
I'm not going to lie I don't understand what you're trying to say. Would you be able to rephrase it more clearly, perhaps with a screenshot illustrating what you mean?

**Comment by Hebgbs** [comment]
I mean, exactly what I said. The pre-rendered  default colour option images for all things which aren't _Custom_ don't need to be there. At least, in my iteration of `numix-colors` there appear to be images for the default selection of available colours which _aren't_ custom, and I believe them to be a waste of space when the custom routine works just fine, and you can pare down the application, as well its overall package size by omitting this and keeping only the options fr custom colour, making the default selection only presets for the custom routine.

Unless I am delusional. I will have to look again but I _swear_ I've seen duplicate files with slightly different names because they're different colours.

**Comment by Hebgbs** [comment]
Yeah, here's what mean: Refactor the application so it doesn't rely on pre-fabricated images for default colours. So this would mean, based off of the PPA remove the following:
```/opt/numix-folders/styles/0
/opt/numix-folders/styles/*/*/*/*/blue-*
/opt/numix-folders/styles/*/*/*/*/brown-*
/opt/numix-folders/styles/*/*/*/*/default-*
/opt/numix-folders/styles/*/*/*/*/green-*
/opt/numix-folders/styles/*/*/*/*/grey-*
/opt/numix-folders/styles/*/*/*/*/orange-*
/opt/numix-folders/styles/*/*/*/*/pink-*
/opt/numix-folders/styles/*/*/*/*/purple-*
/opt/numix-folders/styles/*/*/*/*/red-*
/opt/numix-folders/styles/*/*/*/*/yellow-*```

This would leave only the custom files, which the custom routine already colourizes as defined by the user which would shed a fair bit of fat from the overall package. One could also get rid of `/opt/numix-folders/colours` since that isn't really necessary to call upon when everything should be handled in the program anyway, unless that's there for a colourize function via imagemagick but honestly they don't need to be there if the custom option routine was the only thing the program did.

**Comment by Foggalong** [comment]
We're aware of the pkexec vs gksu issue and it's something that'll be addressed if the GUI version is ever returned to (at the moment it is defacto unmaintained).

I'm still not really clear what your main point is though: are you saying to remove all icons except those of the format `*/custom-*.svg` and then just have, for example, the blue folders be a recolouring of those at runtime?

**Comment by Foggalong** [comment]
Closed due to lack of response from original reporter.

If what I said above _was_ your question, then the reason we don't do that because they're there as part of the Folder Colors application; they're not here just for use with this app.
