### ISSUE TITLE
Change folder icon (files)

### ISSUE THREAD

**Issue by arah24** [numixproject/numix-folders#189]
Would it be possible to replace files icon in numix-circle? 

Changing the default one which has a horrendous purple background to something more simpler?

[The default one](https://imgur.com/VELcb3V)

To something like this?

[Modified version](https://imgur.com/M0enD0W)

**Comment by palob** [comment]
Are you referring to the background colour of the Numix Circle icon?
We ship different colours. Go to where Numix Circle/Square is installed and search for ``file-manager``. You'll find some alternative colours.
Now look up and open the ``.desktop`` laucher file and change the icon line to ``file-manager-red`` for instance.

If you want to change the colour of the folder itself, this is the very purpose of numix-folders.

**Comment by arah24** [comment]
I did a find on the `file-manager` name in directory or any of the subdirectories. I've done a recursive search on it as well.

**Comment by palob** [comment]
You'll probably find the ``.desktop`` file in ``usr/share/applications``. Copy it to ``~/.local/share/applications`` so you can edit it without root privileges and it is update-persistent.

**Comment by arah24** [comment]
What `.desktop` file am I looking for? I can't seem to find the `file-manager` one in this instance.

**Comment by palob** [comment]
Which file manager do you use? Nautilus, Thunar, Dolphin, Caja, Pantheon Files......?

**Comment by arah24** [comment]
Nautilus.

**Comment by palob** [comment]
In this case you need to look for ``org.gnome.Nautilus.desktop``.

**Comment by arah24** [comment]
Are there any documentations available that suggests when adding a colour extension to the end of the icon name for e.g. `Icon=org.gnome.Nautilus.orange` would show an example of the output ?

I've modified the `org.gnome.Nautilus.desktop` file to have any sort of colour, it changed the folder icon to a blank white folder with the star of david inside which isn't desirable for me.

**Comment by palob** [comment]
Sorry, I do not understand what you are asking for. Adding that "colour extension" won't do anything for sure though.
You need to edit it to ``Icon=file-manager-red`` or ``Icon=file-manager-blue`` or ``file-manager-green``.
That's all alternative colours we've got at the moment.

**Comment by arah24** [comment]
I see thanks!

I've set the Icon to be blue and it seems to be fine for now :+1:
