### ISSUE TITLE
Colour inconsistency between default and the others for folder-copy in style 5

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-folders#19]
There is a colour inconsistency between the default colour and the additional 9 other colours for folder-copy in Folder Style No. 5: In the default colour, the second folder (in the back) is a tad darker than the first folder in the front, whereas for all other colours, the folder colour is the same for both colours.

This applies to all the folder sizes.

Default colour (a tad darker in the back):

![default-folder-copy_5](https://cloud.githubusercontent.com/assets/7164227/6483181/587a069c-c26e-11e4-83f0-9866dea91448.png)

E.g. grey (same colour in front and back; this goes for all other non-default colours as well):

![grey-folder-copy_5](https://cloud.githubusercontent.com/assets/7164227/6483186/67da3cf6-c26e-11e4-8a0f-4b7390d28150.png)

This is an inconsistency that does not exist for Folder Styles 1,2,3,4 or 6. Not all of these styles use (a bit) different folder colours for folder-copy, but they all follow the same design consistently with all 10 colours, default and non-default all the same.

Style No. 1 (consistently the same folder colours, default example):

![default-folder-copy_1](https://cloud.githubusercontent.com/assets/7164227/6483190/6dbed6ae-c26e-11e4-9a16-2d78cd3aa07c.png)

Style No. 2 (consistently a tad darker for the back folder, default example):

![default-folder-copy_2](https://cloud.githubusercontent.com/assets/7164227/6483198/85cc30f2-c26e-11e4-8e2f-8f105e594eb1.png)

Style No. 3 (consistently a tad darker for the back folder, default example):

![default-folder-copy_3](https://cloud.githubusercontent.com/assets/7164227/6483204/97367190-c26e-11e4-92f9-dba20e0fc4b8.png)

Style No. 4 (consistently a tad darker for the back folder, default example):

![default-folder-copy_4](https://cloud.githubusercontent.com/assets/7164227/6483208/9c200450-c26e-11e4-9e4f-4c00ffc50400.png)

Style No. 6 (consistently the same folder colours, default example):

![default-folder-copy_6](https://cloud.githubusercontent.com/assets/7164227/6483210/a154ecf6-c26e-11e4-9201-991160e86bd5.png)

**Comment by wa4557** [comment]
@Foggalong what do you prefer for this in style 5? Darker second folder for all the other colors, or same color for the second folder, for the default color?

**Comment by Foggalong** [comment]
@wa4557 Match style 5 to style 6, so just make the defaults the same :)
