### ISSUE TITLE
Installation question

### ISSUE THREAD

**Issue by gamesbook** [numixproject/numix-folders#192]
The install says "To use the script simply download this repo, move into the repos directory" - where exactly would I find this "repos" directory when running Mint (v19)?

**Comment by gamesbook** [comment]
I found instructions elsewhere:
```
sudo apt install git
git clone https://github.com/numixproject/numix-folders
cd numix-folders
./numix-folders
```
However, running the script and selecting a new color did not make any difference. Also trying restarting `nemo` with no effect.

**Comment by palob** [comment]
So I take it your first question is answered?

Does it work if you run numix folders without the GUI by typing ``./numix-folders -t``?

**Comment by gamesbook** [comment]
```sudo ./numix-folders -t
Which folder style do you want? 4
Which folder colour do you want? Blue
gtk-update-icon-cache: Cache file created successfully.
gtk-update-icon-cache: Cache file created successfully.
Folder change complete!
```
Worked perfectly!

(note to self: **always** trust the command line...)

**Comment by gamesbook** [comment]
_So I take it your first question is answered?_

Indirectly, yes. It would be great if the front page was updated with these instructions to make it easier for the next person.

**Comment by palob** [comment]
Well, as with any Github repo there's the *Clone or download* button. If you choose *Download ZIP* it depends on your browser (settings) where the file will be saved. Usually the standerd setting is the *Downloads* folder of your HOME directory.

Regarding question 2, does this mean the GUI does not work for you?

**Comment by gamesbook** [comment]
The GUI has not worked when I tried it.
