### ISSUE TITLE
Icon for folder-open only a symlink for default colour and missing for all non-default colours in Tilted Design No. 3

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-folders#21]
For Tilted Design No. 3, there is a problem with the icon for folder-open: For the default colour, `default-folder-open.svg` is only a symlink to `default-fileopen.svg`. And for all non-default colours, `default-folder-open.svg` is missing completely.

This applies to all folder sizes.

Comparative screenshots of Tilted Style No. 3 and Style No. 4 in Files/Nautilus, searching for "open" in `Numix/48x48/places`:

Tilted Style No. 3:

![open_style-3](https://cloud.githubusercontent.com/assets/7164227/6483714/7b2d5648-c274-11e4-80c4-a60dff839ce1.png)

Style No. 4 (and all the other folder styles):

![open_style-4](https://cloud.githubusercontent.com/assets/7164227/6483806/6771ac16-c275-11e4-8941-6c15839f13ff.png)

**Comment by Foggalong** [comment]
As I explain [here](https://github.com/numixproject/numix-folders/issues/26#issuecomment-77772607), that was actually intentional. IIRC when we looked at it 4 looked a bit weird when being open without the documents in, so we just had it be the same.
