### ISSUE TITLE
Inconsistent icon for document-open and for document-open-recent

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-folders#23]
In Styles No. 2 and  No. 4 and possibly also in Style No. 6, the icon for document-open and for document-open-recent is inconsistent.

In Styles No. 1, 3 and 5, for these two icons in `.../actions`, the same (consistent) icon is used as for fileopen in `.../places`.

But in Styles No. 2 and No. 4, the same icon is used as for folder-open in `.../places`. Yet, document-open refers to opening a document and not to opening an entire folder, so this is potentially misleading:

Style No. 2 `48x48/actions`

![2_actions](https://cloud.githubusercontent.com/assets/7164227/6493247/c10062a6-c2b9-11e4-81a0-33fedff9904f.png)

Style No. 2, `48x48/places`

![2_places](https://cloud.githubusercontent.com/assets/7164227/6493251/c686137e-c2b9-11e4-9f7f-6b882d3acb74.png)

Style No. 4, `48x48/actions`

![4_actions](https://cloud.githubusercontent.com/assets/7164227/6492877/cde95e8a-c2b6-11e4-9dc1-230189919df5.png)

Style No. 4, `48x48/places`

![4_places](https://cloud.githubusercontent.com/assets/7164227/6492882/d2530f66-c2b6-11e4-9464-ef94a8862c37.png)

In Style No. 6, also not the same icon as for fileopen is used, but here this is also not the very same icon as for folder-open (that one incluces an arrow pointing upwards), so this could be intentional:

Style No. 6, `48x48/actions`

![6_actions](https://cloud.githubusercontent.com/assets/7164227/6492883/d618c2c6-c2b6-11e4-812e-bb537ff368e9.png)

Style No. 6, `48x48/places`

![6_places](https://cloud.githubusercontent.com/assets/7164227/6492887/da8c7686-c2b6-11e4-99b0-b384fead3343.png)

In contrast, Styles No. 1, 3 and 5 are using the same (consistent) icon for document-open (and document-open-recent) in `.../actions` as for fileopen in `.../places`.

Style No. 1

![1_actions](https://cloud.githubusercontent.com/assets/7164227/6493122/e5ba0d5a-c2b8-11e4-9324-8744487dda60.png)

Style No. 3

![3_actions](https://cloud.githubusercontent.com/assets/7164227/6493128/eac7ff3c-c2b8-11e4-967e-43e1254d7113.png)

Style No. 5

![5_actions](https://cloud.githubusercontent.com/assets/7164227/6493130/ef62b6a4-c2b8-11e4-9e6e-068e39feb81d.png)

Well, since this a kind of a tie (3 to 3), this all could be intentional after all :-) Still reporting it, because to me the document-open (actions) and fileopen (places) icon is a consistent combination.

**Comment by dirtydancing** [comment]
To illustrate this issue with the example of Gedit in Ubuntu 14.10:

In the menu bar, the second icon from the left, apparently size 24, is "open a file" (text shown when hovering over). With Style No. 5, this is easily recognizable as a file, whereas e.g. in Style No. 6 and in Style No. 4 this is somewhat unclear.

Please also note that, when compared to the other icons, the folder icon size/shape fits best overall with Style No. 5 in this example, but again this might just come with the somewhat different intended designs of the Styles.

Finally, please note that the icon is the wrong one for Style No. 4, which has already been addressed in https://github.com/numixproject/numix-folders/issues/25

Style No. 5 (correct)

![gedit_5](https://cloud.githubusercontent.com/assets/7164227/6541050/f62ddd04-c4bd-11e4-92a8-02ea3117b3a9.png)

Style No. 6 (questionable)

![gedit_6](https://cloud.githubusercontent.com/assets/7164227/6541057/07c16a0e-c4be-11e4-9f0e-334f0a384c8f.png)

Style No. 4 (inconsistent)

![gedit_4](https://cloud.githubusercontent.com/assets/7164227/6541058/20ddf05c-c4be-11e4-8120-624631d6b423.png)

**Comment by wa4557** [comment]
Just a comment: merging my branch will not fully close this issue, since only style do is done at the moment. I got a little bit confused by the different bugs :)
