### ISSUE TITLE
Colour contrast issue with green on green for colour green in Styles No. 6 and No. 5

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-folders#24]
For Styles No. 6 and No. 5, in `actions` for colour green, the additional green elements for `green-add-folders-to-archive.svg`, `green-document-open-recent.svg` and `green-folder-new.svg` are hardly visible at all.

This is because these green elements are of a different green in Styles No. 6 and No. 5 when compared to Styles No. 1-4. The contrast for the different colours is sometimes better and sometimes not ideal, but especially for this green on green, the elements become almost invisible.

I would suggest for just these two special cases in Styles No. 6 and No. 5 and just for the green folder colour to make the contrast more visible by e.g. making the green for the additional green elements darker.

Comparative screenshots of Styles No. 6 and No. 5 and then of Styles No. 1-4 (as an example in folder size 24x24, but this goes for all folder sizes):

Style No. 6 (problem)

![6_24](https://cloud.githubusercontent.com/assets/7164227/6503484/d4dd3ed8-c32d-11e4-9d38-141cbe11e353.png)

Style No. 5 (problem)

![5_24](https://cloud.githubusercontent.com/assets/7164227/6503485/d97632e2-c32d-11e4-9f77-45e403550166.png)

Style No. 1 (ok)

![1_24](https://cloud.githubusercontent.com/assets/7164227/6503487/dec92434-c32d-11e4-8c46-a69b43a17a6a.png)

Style No. 2 (ok)

![2_24](https://cloud.githubusercontent.com/assets/7164227/6503490/e2bfeb72-c32d-11e4-9fdf-e2da828582e1.png)

Style No. 3 (ok)

![3_24](https://cloud.githubusercontent.com/assets/7164227/6503492/e6d2d5ee-c32d-11e4-8e8e-8deb1c62c5f0.png)

Style No. 4 (ok)

![4_24](https://cloud.githubusercontent.com/assets/7164227/6503494/ebc35a92-c32d-11e4-98fd-bdf82ea36cf8.png)

**Comment by Foggalong** [comment]
Unfortunately a wontfix. There are indeed problems with the contrast for that style, and in other places too, but it would be way too much work to have a colour scheme that worked for emblems too for every colour, especially as it also has to stay consistent with the base theme.
