### ISSUE TITLE
Wrong folder icon in actions in sizes 16, 22 and 24 in style 4

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-folders#25]
In Style No. 4, for sizes 16, 22 and 24, in `actions` the icons for `document-open` and for `document-open-recent` are wrong. They feature the regular folder icon, just as `folder-new` right next to them.

The correct icon would not be the folder icon, but rather fileopen/folder-open, which one exactly for Style No. 4 depends on how https://github.com/numixproject/numix-folders/issues/23 is addressed.

This applies to all colours.

Style No. 4, `Numix/24x24/actions` (incorrect, as also sizes 16 and 22)

![4_24](https://cloud.githubusercontent.com/assets/7164227/6512022/28eab08a-c371-11e4-8a64-0ba1179727de.png)

Style No. 4, `Numix/32x32/actions` (correct, as also all the larger sizes)

![4_32](https://cloud.githubusercontent.com/assets/7164227/6512025/2cb9da06-c371-11e4-8385-d609d1f45b84.png)

Comparison: Style No. 5, `Numix/24x24/actions` (correct)

![5_24](https://cloud.githubusercontent.com/assets/7164227/6512027/30474e24-c371-11e4-8411-41cc6e91525c.png)

**Comment by wa4557** [comment]
This should be fixed by merging my branch, got confused by #23
