### ISSUE TITLE
Plain folder shape varies considerably in different sizes in Style No. 6

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-folders#28]
This is not necessarily an issue with Numix folders at all, but rather an observation of the folder icons in practice:

In current default Style No. 6, the plain folder shape (i.e. the plain folder without symbols) varies considerably e.g. inbetween sizes 48, 32 and 16. This might be a completely intentional design choice, but e.g. for my personal taste, in Style No. 6 the plain folder does look somewhat large in size 16.

This probably intentional design choice also has consequences e.g. for folder icons that have been manually selected e.g. for extra folders in the Home directory in Files/Nautilus in Ubuntu. Here is an example from current Ubuntu 14.10 comparing Style No. 6 (problem) with Style No. 5 (fine). Again, also this is not necessarily a Numix issue, but rather a Nautilus issue, but still this appears to be a rather common use case. I am only comparing the two latest Styles No. 6 and No. 5 here.

Apparently, Files/Nautilus in Ubuntu (14.10) "hardcodes" a manually selected icon that is selected via the standard way of going into the folder properties, clicking on the folder icon and selecting an icon for that folder. "Hardcodes" in this context means that the icon stays the same and is scaled up and down to all different sizes, whereas the default folder icons get picked according to their respective sizes without the need for additional scaling.

In preparation, here come three screenshots of the plain folder in sizes 48, 32 and 16 in Styles No. 6 and No. 5. I have enlarged them so that the canvas is of the same size in the screenshot. It is obvious that the plain folder shape in Style No. 6 varies considerably (gets quite larger in relation to the canvas as the icon size gets smaller), whereas the plain folder shape in Style No. 5 stays just about the same throughout the different sizes.

Style No. 6, 48x48

![6_48](https://cloud.githubusercontent.com/assets/7164227/6537782/996c87f4-c45a-11e4-9893-440111dc3f58.png)

Style No. 6, 32x32

![6_32](https://cloud.githubusercontent.com/assets/7164227/6537783/9dc44daa-c45a-11e4-8173-2c527ace0789.png)

Style No. 6, 16x16

![6_16](https://cloud.githubusercontent.com/assets/7164227/6537786/a26fa34a-c45a-11e4-9147-46990f3294f9.png)

Style No. 5, 48x48

![5_48](https://cloud.githubusercontent.com/assets/7164227/6537793/acca858a-c45a-11e4-8473-59e8b55cb7e4.png)

Style No. 5, 32x32

![5_32](https://cloud.githubusercontent.com/assets/7164227/6537799/b067abc8-c45a-11e4-8be6-4eeda65ce325.png)

Style No. 5, 16x16

![5_16](https://cloud.githubusercontent.com/assets/7164227/6537802/b5230c84-c45a-11e4-9e95-b04cdac4515f.png)

And now, here come three screenshots of Files/Nautilus in Ubuntu 14.10 with Styles No. 6 and 5. The first one is the default grid view (apparently size 48). This is the size in which I have manually selected the 48x48 folder icon for wine and vm. The second one is the default list view (apparently size 32). The third one is the smallest icon size in grid view (apparently size 16).

For Style No. 6, just as expected, in the default grid view (48) all folder icons look the same, including wine and vm. But for list view (32), as the size 48 folder icon is scaled down to 32, the folder icons for wine and vm look somewhat smaller and "inconsistent". And for the smallest icon size in grid view (16), the folder icons for wine and vm look very different from the usual (unscaled) plain folder icons.

![6_grid_default](https://cloud.githubusercontent.com/assets/7164227/6537810/c555bcc8-c45a-11e4-8bfa-0e839f2c3df2.png)

![6_list_default](https://cloud.githubusercontent.com/assets/7164227/6537889/8f617c32-c45b-11e4-838d-8fedb9d021b0.png)

![6_grid_smallest](https://cloud.githubusercontent.com/assets/7164227/6537818/d084367e-c45a-11e4-9421-cbd30f04a39e.png)

For Style No. 5, in contrast, as the plain folder shape stays about the same in sizes 48, 32 and 16, in all three screenshots the folder icons, even if scaled down for wine and vm, look "constistent" and in line with the other default folder icons (that get picked respectively for each size that they have been designed for).

![5_grid_default](https://cloud.githubusercontent.com/assets/7164227/6537823/db1e593e-c45a-11e4-812e-d389f8f5ca7b.png)

![5_list_default](https://cloud.githubusercontent.com/assets/7164227/6537826/df7ebe24-c45a-11e4-8264-03e34a839cc1.png)

![5_grid_smallest](https://cloud.githubusercontent.com/assets/7164227/6537831/e6ab142c-c45a-11e4-8a9c-54eab8f3f01b.png)

**Comment by dirtydancing** [comment]
Regarding Nautilus/Files: The behaviour to "hardcode" manually selected folder icons exists in Ubuntu 14.10 with Nautilus 3.10.1 as well as in daily (in development) Ubuntu 15.04 with Nautilus 3.14.2.

**Comment by Foggalong** [comment]
Yeah, as you say from what I understand this is an issue with Nautilus rather than Numix. Nautalius should be getting the icons from the 16px directory in that example, rather than scaling the 48px one. This causes much bigger problems than inconsistent shapes, such as incomprehensible symbols.
