### ISSUE TITLE
Visual inconsistency with folder-ubuntu.svg in style 5

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-folders#32]
I just noticed a slight inconsistency with the Ubuntu symbol in `folder-ubuntu.svg` in style 5: the Ubuntu symbol appears to be a little too thin/small when compared to the other folder symbols.

I do not have this impression e.g. in style 6, all fine there.

This relates to the already reported and fixed https://github.com/numixproject/numix-folders/issues/10, but it is not as obvious and quite possibly only a subjective impression of mine. Still reporting this, just in case.

Screenshot in the important icon size 48x48 (e.g. default in Nautilus):

![ubuntu-1504_style-5](https://cloud.githubusercontent.com/assets/7164227/6628392/5642aaa8-c905-11e4-84e0-6d447aa7a4a4.png)

Screenshot with folder overview, comparison e.g. to `folder-recent.svg`:

![style-5](https://cloud.githubusercontent.com/assets/7164227/6628605/32a9fe32-c907-11e4-89fa-57643a1f3fae.png)

In contrast, the same folder overview with style 6, all fine there:

![style-6](https://cloud.githubusercontent.com/assets/7164227/6628612/43e2a848-c907-11e4-9557-023509bc1560.png)

**Comment by Foggalong** [comment]
There's just not enough room to have the Ubuntu symbol as big as the recent one for style 5 :( If it gets any bigger it either crops of the left bobble or stretches out too much to the right, sorry

**Comment by dirtydancing** [comment]
Yeah, makes sense, thanks!
