### ISSUE TITLE
folder color support

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-folders#4]
Hello, i use usualy folder-color on my ubuntu 14.10 to change the color of some folders to make things look nice. 
i would like to ask if it's possible to support it with numix folder colors :D
the officiel web site  : http://foldercolor.tuxfamily.org/
the folder color are here : /usr/share/folder-color/media
it would be really so cool to see those colored folders with a numix style 
![capture du 2014-10-16 13 09 16](https://cloud.githubusercontent.com/assets/7660997/4661536/edbcb22a-5524-11e4-8de8-dfd306d92f7e.png)

Thank you so much :D

**Comment by Foggalong** [comment]
Fixed in [ae1b3fafed575a73c4beb85fa92109aff42ae285](https://github.com/numixproject/numix-icon-theme/commit/ae1b3fafed575a73c4beb85fa92109aff42ae285
