### ISSUE TITLE
How to keep the selected non-default folder style over Numix base PPA updates

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-folders#45]
Question: is there a way to keep the selected non-default folder style over Numix base PPA updates?

So far, after every PPA update (in daily sequence when there are a lot of changes), the folder style is reset to the default style 6. As I am using curvy style 5, I am currently running the script every time again.

**Comment by Foggalong** [comment]
Not without doing something like [Ozon](https://github.com/ozonos/ozon-icon-theme-folders/tree/master/Ozon-Colored) where each style is a separate theme. That has potential to cause problems with inheritance with Numix and would mean loads and loads of themes if colours are taken into account.

**Comment by dirtydancing** [comment]
Alternatively, might there be a way to trigger the script automatically when an update is detected? This automatic triggering of the script should only happen if a non-default folder style has been selected via the script before (i.e. not for the default style, as that will be displayed per default anyways). Just an idea.

**Comment by Foggalong** [comment]
That's possible, but it would add a lot of baggage to the script such as an installer and a need for it's own data directory.

**Comment by Foggalong** [comment]
Gonna say no to this. While it'd be an awesome feature to have, the overhead would be too significant to implement :(

**Comment by bil-elmoussaoui** [comment]
@Foggalong I guess you can create a  folder in .config or a hidden file where you put the default values as default style, default color. Whenever the ppa updates, you check if the file exists if so, gets get back folder to it's default values. If not, keep the default one. This might not be that hard to do

**Comment by Foggalong** [comment]
That's not really the hard bit - it would involve setting up a system to watch for PPA updates which is out of the scope of this project :(

**Comment by dirtydancing** [comment]
Cf. the further discussion over at #101.
