### ISSUE TITLE
Folder naming for "Google Drive" is inconsistent

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-folders#48]
In continuation of https://github.com/numixproject/numix-folders/issues/44: The folder names for "Google Drive" are `gdrive` in sizes 48x48 and 96x96, but in contrast `google-drive` in all other sizes.

There should be one consistent name, arguably `google-drive` (as `gdrive` seems to be the exception).

**Comment by Foggalong** [comment]
Yeah, the intended one was `google-drive`, `gdrive` was the name of the original user contributed one that we modified slightly :)
