### ISSUE TITLE
Cleanup and Colours

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-folders#5]
Carried across from [#4](https://github.com/numixproject/numix-folders/issues/4) and [#204](https://github.com/numixproject/numix-icon-theme/issues/204). Work on this is being done in the [rainbow](https://github.com/numixproject/numix-folders/tree/rainbow) branch.

This is a total todo list for this issue, sorted by priority:

* [x] Clean up style 1 [4fe8cc4bd9ea109c0af209893dfe9c06fabfc571]
  * [x] Clean up 16x16 style 1 (26 icons) [c3d173b4115cd1d29bbeb09f86d03bf4a64d11b7]
  * [x] Clean up 22x22 style 1 (26 icons) [1308a1ec4d2e9b37ebc7d18d8d3d61d835c95d6a]
  * [x] Clean up 24x24 style 1 (26 icons) [8716cbbc3c75184965c0c1ab417395fd73e443a0]
  * [x] Clean up 32x32 style 1 (26 icons) [6790e7fb4c554fc8c2c91eb20f93708338553e56]
  * [x] Clean up 48x48 style 1 (26 icons) [64927120d438cb77e078034073c8e216e5d58157]
  * [x] Clean up 64x64 style 1 (26 icons) [7544cce8adba40921ed3b13f589e87669c2c4ab9]
  * [x] Clean up 128x128 style 1 (26 icons) [0c289ac2c309369e4da75bbb96827aaf94e7ee98]
  * [x] Clean up 256x256 style 1 (26 icons) [137e9a0e66af184f4f2241b590aec3962d858dc7]

* [ ] Clean up style 4
  * [x] Clean up 16x16 style 4 (26 icons) [1f374175b0e82aaf4731a4cd5f90cda8611ff2a2]
  * [ ] Clean up 22x22 style 4 (26 icons)
  * [ ] Clean up 24x24 style 4 (26 icons)
  * [ ] Clean up 32x32 style 4 (26 icons)
  * [ ] Clean up 48x48 style 4 (26 icons)
  * [ ] Clean up 64x64 style 4 (26 icons)
  * [ ] Clean up 128x128 style 4 (26 icons)
  * [ ] Clean up 256x256 style 4 (26 icons)

* [ ] Figure out style merge
  * [ ] Look into merging 2 into 1
  * [ ] Look into merging 3 into 4 (or vis versa)

* [ ] Implement recolouring into the script

* [ ] Add "Folder Color" Support
  This is a list of the needed icon names for adding "Folder Color" support, for each $COLOR in black, blue, brown, cyan, green, grey, orange, pink, purple, red, white, yellow.

  * folder_color_$COLOR_desktop
  * folder_color_$COLOR_desktop.svg
  * folder_color_$COLOR_documents.svg
  * folder_color_$COLOR_downloads.svg
  * folder_color_$COLOR_music.svg
  * folder_color_$COLOR_pictures.svg
  * folder_color_$COLOR_public.svg
  * folder_color_$COLOR.svg
  * folder_color_$COLOR_templates.svg
  * folder_color_$COLOR_videos.svg
  * folder_color_custom.svg

  * [ ] Add support in style 1
      * [ ] Support 16x16 (132 icons)
      * [ ] Support 22x22 (132 icons)
      * [ ] Support 24x24 (132 icons)
      * [ ] Support 32x32 (132 icons)
      * [ ] Support 48x48 (132 icons)
      * [ ] Support 64x64 (132 icons)
      * [ ] Support 128x128 (132 icons)
      * [ ] Support 256x256 (132 icons)
  * [ ] Add support in style 2
      * [ ] Support 16x16 (132 icons)
      * [ ] Support 22x22 (132 icons)
      * [ ] Support 24x24 (132 icons)
      * [ ] Support 32x32 (132 icons)
      * [ ] Support 48x48 (132 icons)
      * [ ] Support 64x64 (132 icons)
      * [ ] Support 128x128 (132 icons)
      * [ ] Support 256x256 (132 icons)

If we can merge styles, this is a 2528 icon issue. If we can't, it's a 5056 icon issue. I think this might just be our biggest issue yet :P

**Comment by Foggalong** [comment]
@costales is the information here still accurate? http://bazaar.launchpad.net/~costales/folder-color/trunk/view/head:/README

**Comment by costales** [comment]
Hi @Foggalong |o/ How are you? :)

I updated just now (same URL). Because I removed the black color.

I'd recommend you to use the same color names: Brown, Blue, Green, Grey, Orange, Pink, Red, Purple and Yellow.
Why? Because if Numix will have "Metal" color (by example) the user'll see it, but if the user changes to other theme, the icon will not exists and he'll see a blank page (no icon available).

Please, ask me any doubt :) If you do a beta, I could try it.

FYI: Folder Color is in the Ubuntu repository now and it's available for Nautilus, Nemo & Caja!! :)
http://packages.ubuntu.com/vivid/folder-color

Cheers!

**Comment by Foggalong** [comment]
Good thanks! How are you? :)

These are the colours we've gone for:
![screenshot - 300115 - 16 12 51](https://cloud.githubusercontent.com/assets/5920259/5978852/e8873fb8-a89a-11e4-995f-4fd7442597a7.png)

**Comment by costales** [comment]
They look really awesome! :)
"folder_colour_default.svg" will not be used. By the name and because 
*_default.svg it's not a valid extension for Folder Color ;)
Cheers!

**Comment by Foggalong** [comment]
Aye, default is going to be switched to custom once I work out how that works. What of  Cyan, Teal, and Black though?

**Comment by costales** [comment]
> Aye, default is going to be switched to custom once I work out how that
> works.

If you want, send me that icon and I'll try a shoot :)


What of Cyan, Teal, and Black though?

They'll work perfect.
But remember this example:
  - User uses Hummanity
  - User installs Numix and set it as default
  - User changes 1 folder to red & 1 folder to cyan
  - User changes to Hummanity (or other) > The user will see these:
     * Red Hummanity icon.
     * No icon for Cyan (Problem: Because it doesn't exist for Hummanity)
  - User changes to Numix again > The user will se the Red & Cyan ;)

**Comment by Foggalong** [comment]
Ah, I see! Thanks :)

**Comment by Foggalong** [comment]
Ah, I see! Thanks :) As an aside, or the listed specific folders the only ones supported? There are quite a few in the Numix theme that aren't listed. It's fine if they're not needed, but thought I'd check before I deleted.

![screenshot - 300115 - 16 26 22](https://cloud.githubusercontent.com/assets/5920259/5979135/ecf00cf4-a89c-11e4-8302-806111282c40.png)

**Comment by costales** [comment]
Good point @Foggalong 
Folder Color is dynamic and it'll work for any standard folder here: ~/.config/user-dirs.dirs (not checked!).

In my case:
costales@desktop:~$ cat ~/.config/user-dirs.dirs | grep XDG
XDG_DESKTOP_DIR="$HOME/Desktop"
XDG_DOWNLOAD_DIR="$HOME/Downloads"
XDG_TEMPLATES_DIR="$HOME/"
XDG_PUBLICSHARE_DIR="$HOME/Public"
XDG_DOCUMENTS_DIR="$HOME/Documents"
XDG_MUSIC_DIR="$HOME/Music"
XDG_PICTURES_DIR="$HOME/Pictures"
XDG_VIDEOS_DIR="$HOME/Videos"

Dropbox or wine are not standard.

@Foggalong If you want, we could try the script for create the color in all the icons :)

**Comment by Foggalong** [comment]
Not a problem, already got a script going :)

**Comment by costales** [comment]
Great :D
