### ISSUE TITLE
Incorrect sizes for some icons in 22x22 for style 5

### ISSUE THREAD

**Issue by wa4557** [numixproject/numix-folders#56]
I found another small bug in style 5 by chance (@dirtydancing it's hard to believe, but you missed something :P).
`*-user-home.svg` and `*-user-desktop.svg` (all colors) in `22x22` are the icons from `24x24` and therefore have the wrong size. 
I'll create a pull request for that

**Comment by dirtydancing** [comment]
Haha, good catch! :)
