### ISSUE TITLE
Rerun script on every numix-theme update

### ISSUE THREAD

**Issue by uloco** [numixproject/numix-folders#64]
I have to rerun this script everytime when there is a new update on `numix-icon-theme`. 
Is there a way to automate this or any other workaround?

**Comment by dirtydancing** [comment]
I think this is a duplicate of https://github.com/numixproject/numix-folders/issues/45 :), so this is arguably a `wontfix`.

**Comment by dirtydancing** [comment]
Cf. the further discussion over at #101.
