### ISSUE TITLE
Provide custom colour folder icons for the custom option of Folder Color

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-folders#65]
Hi, this recent comment of @foggalong caught my attention: https://github.com/numixproject/numix-folders/issues/61#issuecomment-98554860. I am opening a separate issue for this for clarification purposes. @costales and I have been in contact about the custom colour option as well.

So is this happening now for Numix icon theme? That would be great! Especially useful for colours that are totally different from the Numix colours on purpose, to stand out. Then again, as far as I am aware, currently there is only a "custom color icon" for default style 6 in size `48x48`.

Or is this about a custom colour global/default option from Numix's side?

**Comment by Foggalong** [comment]
This is about a global option from the Numix side.

**Comment by dirtydancing** [comment]
Ah, ok, closing this issue then.

As I understand it, the individual custom folder colour option in Folder Color comes to a limitation for more "complex" folder designs with more colours such as e.g. Numix style 5. Anyways, if this should become an individual folder option in the future, that would still be great, so please feel free to re-open :)
