### ISSUE TITLE
Add chart with default folder colours to Readme

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-folders#66]
In continuation of my comment over at https://github.com/numixproject/numix-folders/pull/63#issuecomment-98683695, I would like to suggest to add a colour chart with the default folder colours.

Actually, this might also allow to specify "old" default colours, so e.g. https://github.com/numixproject/numix-folders/issues/7 could be solved by the user specifying the "old" colours.

**Comment by Foggalong** [comment]
The plan is to just make those styles available by default, rather than having to make the user put the options in manually. It's just a matter of getting around to it :P

**Comment by Foggalong** [comment]
Classing this as wontfix because it's to be done with #7
