### ISSUE TITLE
Inconsistent use of a second colour in some icons in style 1

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-folders#68]
This issue came up in a conversation over here: https://github.com/numixproject/numix-folders/pull/63#issuecomment-99610430. Apparently, style 1 is using one colour as its folder colour. But for some icons, a second colour is added. This employment of a second colour seems to be unnecessary and leads to complications with the option of a default custom colour, cf. the thread referred to above.

The relates to the following icons:

`actions/add-folders-to-archive`
`actions/document-open`
`actions/document-open-recent`

`places/fileopen`
`places/folder-open`

and possibly
`places/folder-move`

In addition, it seems that this colour is wrongly lighter for some icons in the default folder colour, whereas it is rightly darker in the other colours.

Exemplary screenshot:

![style1](https://cloud.githubusercontent.com/assets/7164227/7504698/96cd20c2-f44c-11e4-8a95-1c3ab83c42fc.png)

To address this, it might be recommendable to use a shading of some kind that is overlayed over the single folder colour in style 1. Style 2 might serve as an example for that. And for a lighter colour, this might be handled with less opacity of the primary colour. By using one primary colour consistently and using this one colour also for the icons mentioned above, the icon design gets simpler and is better to customize.

As you can tell from the referred conversation, it is not entirely clear how these colours are used in style 1 and why there is a secondary colour, or if this is used on purpose (in which case this issue might be a non-issue after all). Anyways, this inconsistency seems to be present only in style 1.

**Comment by wa4557** [comment]
It seems that it was intended that only one colour is used cf. #6. It's also inconsistent for different sizes (256/128 vs. all the other sizes)
![unbenannt](https://cloud.githubusercontent.com/assets/6475757/7505211/d67ab492-f450-11e4-88d4-db155e65417e.png)
![unbenannt2](https://cloud.githubusercontent.com/assets/6475757/7505213/d8dc4322-f450-11e4-91e6-5e17d5968f17.png)
