### ISSUE TITLE
Brown folder design?

### ISSUE THREAD

**Issue by wolflambert** [numixproject/numix-folders#7]
I personally like both design 4 (the new one of a few months ago) and 6 (the new one that's the standard now) equally, so I don't care which one, but I really preferred the old colours. Why was design 4 in that scheme removed? I still have the old script, so I'll probably keep using those.

**Comment by Foggalong** [comment]
Previously we had 2 different folders in the script and 2 different color schemes, making a grand total of 4 different styles. With the refresh of the design I thought it would make sense to add all the folders we've had to the script bringing the total from 2 to 6. Each of these folders also had it's own colour scheme bringing that to 6 too, but then we're also adding support for 'folder color' which means brining the total to 16.

That's 6 folders and 16 color schemes, which under the old system of having each combination as a separate pack would bring the total to 96 different styles. As you can see, that's clearly not possible to maintain. Instead we've took the color schemes out of the equation so each style is just that - the style of the folders (with the default colorscheme and nothing more).

We will in future hopefully make use of the 'folder color' support to allow users to change to any of the supported color schemes as a default using the script, but at the moment it's not probable that it will be possible to change the color scheme of one style to that of another.

**Comment by Foggalong** [comment]
As an aside, I really liked the old color scheme too and 4old was similarly my style of choice. If I find an easy way, I will make the option mentioned in the last paragraph possible but with everything else going on at the minute it's not n priority.

If you ever use your copy of the old folders I've kept them in my Numix Labs.

**Comment by wolflambert** [comment]
I understand. I've kept the script, so I can still change to the old "4" style. Does the folder colour tool support changing the default colour though?

**Comment by Foggalong** [comment]
Folder Color allows the changing of any folder to any supported colour, which means we have to make all the folders (every style and size) in every supported colour. Folder Color itself doesn't allow the changing of the default colour, but being as we'll alread have the icons needed that bit should be trivial to implement in our script.

**Comment by wolflambert** [comment]
Great!

**Comment by emariz** [comment]
I really dislike the new Cheetos folder, and thanks to this script I can return to the former design (4) or try another one with a sane colour palette (3).

I also want to let you know that the script always ends with an error (related to *basename*) if I run it as an administrator using an absolute path with the command `su -c '/path/script.sh' `. Note that I am using Debian and that *sudo* is not even installed.
If I use a relative path, the script runs without problems (say `:/path$ su -c './script.sh'`).

**Comment by wa4557** [comment]
@Foggalong is this something you want to happen? It should be incredibly easy to do this now. Would you like to have it like the other colours (i.e. 6 additional colours for each style -> a lot of additional files) or would you like to have it as an option that generates these icons on the fly?

**Comment by Foggalong** [comment]
@wa4557 I was gonna just add the files, but that could work too! Lets see the pull :)

**Comment by Foggalong** [comment]
As of f6ac60a95699e78cffa19d5cfd8e2dbe8ae0bf69 this is now fixed :D
