### ISSUE TITLE
Simpler Code

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-folders#74]
It would be nice if [this section of code](https://github.com/numixproject/numix-folders/blob/master/numix-folders#L121-L233) just read which colours were used in the custom icon for the users chosen style rather than having to state all the colours (and questions) for each case. Reasoning being that this is going to get very unwieldy as more styles (potentially with more colours) are added.

The pseudo code would look something like this:

```python
if "COLOUR_PRIMARY" in "$STYLE"/path/to/custom-folder-videos.svg:
    CODE = ask("Choose primary colour in hex notation: ")
    checkhex($CODE)
if "COLOUR_SECONDARY" in "$STYLE"/path/to/custom-folder-videos.svg:
    CODE = ask("Choose secondary colour in hex notation: ")
    checkhex($CODE)
if "COLOUR_SYMBOL" in "$STYLE"/path/to/custom-folder-videos.svg:
    CODE = ask("Choose symbol colour in hex notation: ")
    checkhex($CODE)

replace_placeholders_with_colours()
# continue from here...
```

**Comment by wa4557** [comment]
I'm not 100% sure I understand what you mean, but I think this is not resonable. If I want to use default values for each style (and I think this is a good idea), I'd still have to do this for each style seperately

**Comment by wa4557** [comment]
Or is it possible to add pngs with the default colours in the respective folders just like for the other colours?

**Comment by wa4557** [comment]
@Foggalong Well this should be closed, shouldn't it? Or is there something else that can be simplified? I'm wondering if it is a good idea to define the default colours in the script or if it would be better to do this using pngs with the colour in the `colours` folder

**Comment by Foggalong** [comment]
@wa4557 I'm wondering if having the default colours listed in the prompt is worth it at all? What are your thoughts?

**Comment by wa4557** [comment]
Initially I was thinking about it without them but I think they should stay. 
First I don't think they are a problem in the code, because if one additional style is added the script needs to be changed with or without them. 
plus if one wants to use for example style 5 with the default symbol colour but different primary colour the default choice is absolutely necessary imo

**Comment by Foggalong** [comment]
Maybe rather than having them listed at that point the colours should be listed when `./numix-folders --colours` is used? That way the code keeps it's simplicity and the user can see all the colours used. That'll work quite well with adding the styles as colour options too (fixing #7)

**Comment by wa4557** [comment]
Mmh, but this will clutter the code even more. Let's say I want to use style 5 with the default symbol color (`fff8e1`) but the primary and secondary colour from style 3. Without the default option (i.e. pressing enter without any option) I have to list each of this colours in the `numix-folders --colours`.

**Comment by Foggalong** [comment]
Ahhh, see what you mean yeah.

**Comment by Foggalong** [comment]
@wa4557 ps, you've still not authenticated your GitHub account ;)
