### ISSUE TITLE
Small typo error in package from ppa

### ISSUE THREAD

**Issue by wa4557** [numixproject/numix-folders#76]
Since you uploaded the numix-folder package to your ppa I suppose it's time to report one small bug

in `/usr/bin/numix-folders` the first line reads

`$#!/bin/bash `

but it should of course read

`#!/bin/bash`

**Comment by Foggalong** [comment]
PPA packaging is still being done so don't worry about this too much yet. All is subject to change :)

**Comment by Foggalong** [comment]
^ @PaoloRotolo ^

**Comment by PaoloRotolo** [comment]
On it :)

**Comment by PaoloRotolo** [comment]
I've just uploaded a fixed version on our [PPA](https://code.launchpad.net/~numix/+archive/ubuntu/ppa) (1.0.2). Thank you!

**Comment by dirtydancing** [comment]
Confirmed that the "not found" line that I referred to e.g. in this comment (with screenshot) https://github.com/numixproject/numix-folders/issues/47#issuecomment-117763833 has been fixed and does not appear anymore :+1:  Checked against Xubuntu 15.04 (VM).
