### ISSUE TITLE
folder style in launcher icon

### ISSUE THREAD

**Issue by uloco** [numixproject/numix-folders#8]
Is there a possibility to change the style of the .desktop file with this script?
Or could you just include new .desktop files for all alternative folder layouts in the numix main icon theme and manage them with this script here.

Because you want to achieve true consistency between all folder icons in the project (as I read in the blogpost on numixproject.org), this would be really great.

**Comment by Foggalong** [comment]
I'm assuming you mean icons like these? ![screenshot - 140215 - 20 01 25](https://cloud.githubusercontent.com/assets/5920259/6200879/5247395e-b484-11e4-89fd-6e05eb2fb5c9.png)

**Comment by me4oslav** [comment]
Yes, we will make all of these consistent. BTW, I will redo file roller to not use any folder style.

**Comment by uloco** [comment]
I don't know if you understood what I was meaning. I am using the curvy folder design (no. 5) and want to have it in my launcher icon / .desktop file show up exactly. When I run this script, it should replace the icon of nautilus automatically.

**Comment by Foggalong** [comment]
@uloco Yeah, that should now happen. Download the latest version of the script and try :)

**Comment by uloco** [comment]
Works like a charm, thank you :)

**Comment by Foggalong** [comment]
Not a problem!
