### ISSUE TITLE
Use 100% opacity for all symbol colours

### ISSUE THREAD

**Issue by wa4557** [numixproject/numix-folders#83]
Just a quick question: Is there a reason why you're using 40% opacity for most of your symbols in style 2,3,4,6 (plus outlines of style 2) instead of 100% opacity. Using complete opaque colours would make recolouring etc. much easier. 

Moreover its inconsistent among different colours / and styles. In style 4 for example you are using completely opqaue colours for some designs/colours; 0.4 opacity for a few others (different for sizes and or colours). 

Would you mind/encourage if I change that accordingly, and use completely opaque colours for all of them? (Just to be clear I wouldn't touch the shadows of course+ the design would stay exactly the same)

**Comment by Foggalong** [comment]
If you fancy making it all consistent then be my guest, the changes are largely there just through being developed over a very long period of time. As long as the design stays the same it sounds like a definite improvement :)
