### ISSUE TITLE
Numix-Colors ;-)

### ISSUE THREAD

**Issue by Sadi58** [numixproject/numix-folders#89]
Thanks for this great utility offering users so many options - for folders in Numix icon theme.

How about renaming this github repository as numix-colors? Or - with or without renaming - adding also a similar script to produce a number of color variations of the great Numix GTK theme???

It should be 10 times easier than the present one changing folder colors/styles.
Even with beginner-level bash scripting skills I've created one for myself and produced a nice Numix-Blue GTK theme simply by replacing all instances of the existing orange color code with the blue color code (the one you use in blue folders) in all relevant css and svg files...

Additionally, I would like to suggest that these scripts create a copy of the base theme, add a color-style suffix to its root folder, and then begin making changes in it.

**Comment by Sadi58** [comment]
And here's my "amateur" script to create a Blue variation from the git repository downloaded/updated locally:

```
#!/bin/bash
#
cp -R "$HOME/.local/share/git/Numix-GTK-Theme" "$HOME/.themes/Numix-Blue"
cd "$HOME/.themes/Numix-Blue"
rm "README.md"
sed -i 's/Numix/Numix-Blue/g' "index.theme"
#
cd "$HOME/.themes/Numix-Blue/unity"
sed -i 's/#[d|D]64937/#42a5f5/g' "close_focused_prelight.svg" "close_focused_pressed.svg" "maximize_focused_prelight.svg" "maximize_focused_pressed.svg" "minimize_focused_prelight.svg" "minimize_focused_pressed.svg" "progress_bar_fill.svg" "unmaximize_focused_prelight.svg" "unmaximize_focused_pressed.svg"
#
cd "$HOME/.themes/Numix-Blue/gtk-2.0"
sed -i 's/#[d|D]64937/#42a5f5/g' "gtkrc"
#
cd "$HOME/.themes/Numix-Blue/gtk-3.0"
rm "thumbnail.png"
sed -i 's/#[d|D]64937/#42a5f5/g' "gtk.css" "gtk-dark.css"
#
cd "$HOME/.themes/Numix-Blue/gtk-3.0/assets"
sed -i 's/#[d|D]64937/#42a5f5/g' "checkbox-checked.svg" "checkbox-checked-dark.svg" "checkbox-mixed.svg" "checkbox-mixed-dark.svg" "grid-selection-checked.svg" "grid-selection-checked-dark.svg" "menuitem-checkbox-checked.svg" "menuitem-checkbox-mixed.svg" "menuitem-radio-checked.svg" "radio-mixed.svg" "radio-mixed-dark.svg" "radio-selected.svg" "radio-selected-dark.svg"

```

**Comment by Foggalong** [comment]
That's because such a program already exists, by the name of 'gtk-theme-config'. It's listed as a dependency of the GTK themes so if you have them installed from somewhere like the PPA chances are you already have it. To use it you simply launch it from the command line and then modify the colours through it's interface as you wish :)

**Comment by Sadi58** [comment]
Oh, thanks! I forgot it.
I thought I was obsolete with the new GTK versions...

**Comment by Foggalong** [comment]
It's a little shaky these days, but it still works fine with Numix up to with GTK 3.16 (which is what I use it with).

The theme is being redesigned as we speak as well as being rewritten in SASS. Whether it will work with this new version is uncertain, but if it doesn't we will more than likely replace it with something that does.

**Comment by Sadi58** [comment]
Thanks.
I just gave it a try again.
It did replace orange selection color with blue but it cannot change the orange color in assets (checkboxes, radiobuttons, progressbars, etc.) naturally.
So my basic script above works better ;-)
I hope the next version takes care of everything...

**Comment by Foggalong** [comment]
Well that's weird. What DE are you using it with? It recolours assets just fine for me :(

**Comment by Sadi58** [comment]
Unity under Ubuntu 15.04 64-bit
