### ISSUE TITLE
Problem with folder-symbolic.svg in Curvy Design No. 5

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-folders#9]
Hi, there seems to be a problem with `folder-symbolic.svg` in Curvy Design No. 5 (fantastic one, btw): For some reason, there is a white "paper" part in this icon, which does not correspond to the default folder design (without "paper"), and this is not displayed correctly in Nautilus/Files in Ubuntu 14.10.

Screenshot of the icon, "paper" area marked:
![folder-symbolic_1](https://cloud.githubusercontent.com/assets/7164227/6226566/c7ee223a-b696-11e4-94d6-f37aad542b2e.png)

Screenshot of Nautilus/Files in Ubuntu 14.10 (default Ambiance GTK theme, but this effect is the same with Numix GTK theme):
![folder-symbolic_2](https://cloud.githubusercontent.com/assets/7164227/6226586/f31cf544-b696-11e4-8a53-bd8ccc213440.png)

Thanks for providing these alternative folder styles, this is great work and a welcome enhancement!

**Comment by Foggalong** [comment]
Thanks for bringing this to my attention! I didn't notice it because of the white background Inkscape and my filemanager :P
