### ISSUE TITLE
Switcher script is wrongly overwriting folder_color_*.svg symlinks

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-folders#91]
While experimenting some more with the numix-folders script, I came across a rather strange issue.

I am wondering if someone can reproduce this, or if this is rather an odd problem only on my end:

When using the folder-color Nautilus extension to change the colour of individual folders, I noticed that this did not work for blue and grey, but in contrast this worked for all other colours. This did not make any sense, so I checked again. Beforehand, I had used the numix-folders script to set the global default colour to blue and to grey (as well as to custom), and indeed:

For some reason, whichever global colour was set before, could not be set as individual folder-color anymore. It seems that somehow the target for the `folder_color_*.svg` symlinks is changed when running the numix-folders script. E.g., after having set `purple` as the global folder colour via the numix-folder script, and then setting global `red`, the symlink for `folder_color_purple.svg` will change to the target `red-folder.svg`. When then choosing a global custom colour via the numix-folders script, the target of the symlink `folder_color_purple.svg` will change to `custom-folder.svg`. This goes for all `folder_color_*.svg` symlinks of a given predefined colour.

Again, this will only happen with those colours that have been selected as global colour via the numix-folders script before, whereas the symlink targets for all previously unused colours will stay the same.

@wa4557 Any idea if something in the numix-folders script could be causing this phenomenon?

**Comment by wa4557** [comment]
oO this is weird. I don't think it's a problem in the script, because te script cannot know anything about previous selections because always the whole folder is copied and overwrites all the folder icons...

`cp -rf styles/"${style}"/Numix/* "${dir}"/Numix/`

**Comment by dirtydancing** [comment]
Well, the `folder_color_*.svg` symlinks are located exclusively in Numix base, not in numix-folders. But apparently also these symlinks get modified every time the numix-folders script is run. The first time e.g. `blue` is selected, nothing is noticeable, because blue still points to blue. But when then `red` is selected, blue points to red. And when then `grey` is selected, blue and red point to grey. And so on.

This seems to be independent of the folder style. I have checked with curvy style 5 as well as with default style 6, and this has happened with both. I have no idea what is going on here.

@wa4557 To be sure: Would you fancy to check and see if this happens on your machine as well?

**Comment by wa4557** [comment]
I can reproduce that with nemo :( Absolutely clueless why this happens

**Comment by wa4557** [comment]
Ok I think I know why this happens, but I have actually not a good idea yet how to fix that...

**Comment by wa4557** [comment]
I pushed a pull request that fixes this problem, seems to be ok now. @dirtydancing Can you try as well?

**Comment by dirtydancing** [comment]
Sure thing :) I will check a little later.

**Comment by dirtydancing** [comment]
@wa4557 Confirmed that your pull request is working. The symlink target of `folder_color_*.svg` stays the same with the fix, all working fine, checked with multiple folder colours (and styles). Great! :+1:

**Comment by dirtydancing** [comment]
@Foggalong Now that also this "hidden" bug has been fixed, are you going to go ahead and make the official announcement? In my experience, everything is running very smoothly.

To illustrate just how useful numix-folders is, here is a screenshot of my current Numix folder style.

This is a custom fresh light blue curvy style 5 with Arch/GNOME (3.16), default Adwaita GTK theme, default Adwaita GNOME Shell theme, default Adwaita wallpaper, default Nautilus settings.

![folder-style](https://cloud.githubusercontent.com/assets/7164227/8155860/abc07496-1348-11e5-8daf-ac32dc52cfcb.png)

**Comment by Foggalong** [comment]
I just need to double check all the icons are in the right place in Base and here, and then fix any problems with the packaging. But yeah, all the blocker issues are now fixed :)

**Comment by dirtydancing** [comment]
Great to hear this! :)
