### ISSUE TITLE
Inconsistent code for the .svg files in apps

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-folders#94]
Seeing https://github.com/numixproject/numix-folders/pull/93 by @wa4557, I checked some .svg files in `apps`, and I noticed that e.g. the "gradient bug" (only relevant when editing an already existing file) is still present in `styles/5/Numix-Circle/48x48/apps/nemo.svg`, but not in `file-manager.svg`. For the "gradient bug" cf. https://github.com/numixproject/numix-icon-theme-circle/pull/2240#issuecomment-110940978.

@palob Would it make sense to run what you ran over at https://github.com/numixproject/numix-icon-theme-circle/pull/2262#issue-87192041 also for the Circle/Square files in `apps` here in numix-folders?

And is https://github.com/numixproject/numix-icon-theme-circle/pull/2283 still relevant here as well?

Alas, my question from yesterday over at https://github.com/numixproject/numix-folders/issues/91#issuecomment-111976296 might still have been pre-mature even after the latest "hidden" bug fix :)

What I am getting to with this issue report is: there should be consistency inbetween the files in `apps` in numix-folders and also between Numix-Circle/Square and numix-folders.

**Comment by palob** [comment]
I think applying the procedure to all ``/styles/*/Numix-Circle/48x48/apps`` (and ``/styles/*/Numix-Circle/48x48/apps``) directories would make sense.
Checked a few and some do have the grey objects indeed.

Do you feel like doing it?

**Comment by dirtydancing** [comment]
@palob As I have not used the cleaner script so far at all, I will gladly wait and leave this up to you :)

**Comment by palob** [comment]
I'm working on this right now. In addition to the grey objects, those icons' baseplates are slightly deformed.

**Comment by palob** [comment]
@Foggalong A few symbols on the Square have there shadow just moved down 1px missing the horizontal displacement. I suppose this isn't on purpose?

**Comment by dirtydancing** [comment]
@palob iirc Square has vertical drop shadows, so this should be on purpose.

**Comment by Foggalong** [comment]
Yeah, Square has vertical shadows while Circle has vertical-left shadows.

It's not really relevant to the issue, but a bit of history. It's actually Circle that's the odd one out, not Square. When redesigning Circle & Square we tried having the same vertical shadow system in both but it really didn't look right in Circle, so we switched that to the current system. The Hexagon desktop version also followed the same shadow system as Square and early Circle but it ended up never being released.

**Comment by palob** [comment]
So can I fix the vertical-left shadows for the Square ones?

**Comment by Foggalong** [comment]
Some of them have the wrong shadows!? O.o

**Comment by palob** [comment]
Can't find them anymore, must have been hallucinating. Anyway, in case I find one, I'll fix it.

**Comment by Foggalong** [comment]
Thanks! :dancer:

**Comment by dirtydancing** [comment]
Thanks @Foggalong for the history lesson, now I finally know what was behing my issue reports back in the day, cf. https://github.com/numixproject/numix-icon-theme-circle/issues/1007 :)

**Comment by Foggalong** [comment]
Haha, yeah! The beta version was never formally released but a few things like that slipped through the cracks

**Comment by palob** [comment]
@Foggalong or whoever knows it: Is it alright that for styles 5 and 6 ``file-manager-blue.svg`` is darker (actually same colour as ``dolphin.svg``) or should I make the colour lighter, consistent with styles 1 through 4?

**Comment by dirtydancing** [comment]
To me, it looks like this is on purpose once again. Also `file-manager-green.svg` is a lighter green in styles 5 and 6 when compared to styles 1 to 4. Styles 5 and 6 are the newest ones, and also other colours are different for those two styles, e.g. the green elements in the action icons.

**Comment by Foggalong** [comment]
Yeah, it was done on purpose so that the colours didn't clash absolutely horribly.
