### ISSUE TITLE
PNG icons from Base

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-folders#98]
From [this issue](https://github.com/numixproject/numix-icon-theme/issues/450) in base a couple of icons have come up which include folders so come under this repos remit.

* [ ] stock_shared-by-me ![stock_shared-by-me](https://cloud.githubusercontent.com/assets/5920259/8440550/bc444832-1f6a-11e5-85b3-29a2a8ba02e0.png)
* [ ] stock_shared-to-me ![stock_shared-to-me](https://cloud.githubusercontent.com/assets/5920259/8440568/e5350fb0-1f6a-11e5-8ef9-d0e5638164eb.png)

**Comment by Foggalong** [comment]
This could possibly done with `folder-publicshare.svg` but I'm not sure whether the two still need a distinction.

**Comment by wa4557** [comment]
Oh my folder icons are so much work :(
Somehow make the person in front more prominent for `shared-by-me` and the other one for `shared-to-me`? No idea about the exact way to do this however.

**Comment by Foggalong** [comment]
You reckon we could get away with just symlinking them up?

**Comment by wa4557** [comment]
I guess that's justifiable :) :+1:

**Comment by Foggalong** [comment]
:+1:

**Comment by Foggalong** [comment]
Just found that the SVGs are already in base :P removing the PNGs now
